### ISSUE TITLE
ifort segfaults when compiling 1.5.1's libxsmm.f

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#104]
With:
[localhost libxsmm]$ ifort -V
Intel(R) Fortran Intel(R) 64 Compiler XE for applications running on Intel(R) 64, Version 15.0.3.187 Build 20150407
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

Then:
# [localhost libxsmm]$ make realclean && make 
## LIBXSMM master-1.5.1-78

Intel Compiler: icc 15.0.3, icpc 15.0.3, and ifort 15.0.3
C / C++: -msse3
## Fortran: -msse3

[...]
results into:
ifort -threads -qno-offload -fpic -diag-disable 10006,10010,10411,13003 -free -O2 -fp-model fast=2 -align array64byte -DLIBXSMM_BUILD -DNDEBUG -D__STATIC=1 -D_REENTRANT -Iinclude -Ibuild -I/home/aheineck/Projects/LIBXSMM_workspace/libxsmm_internal_merge/src -msse3 -c include/libxsmm.f -o build/intel64/libxsmm-mod.o -module include
include/libxsmm.f: catastrophic error: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for include/libxsmm.f (code 1)

When the Fortran interface is not needed:
[localhost libxsmm]$ make realclean && make FC=
can be used to work-around the problem

**Comment by hfp** [comment]
Checked with IFORT 15.0.3 and it appears to be worked around. Also checked with PGI (`make CXX=pgc++ CC=pgcc FC=pgfortran COMPATIBLE=1 interface`), and it appears to work as well. Let's wait for Travis...

**Comment by hfp** [comment]
I've also setup another test pipeline with Buildkite, which builds/runs the Travis testset using the aforementioned compiler.
