### ISSUE TITLE
libxsmm_barrier_release segfaults when being called without initializing barrier

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#106]
A call to libxsmm_barrier_release segfaults when calling it for a 
a) correctly created barrier but 
b) not initialized barrier (libxsmm_barrier_init was never called)

Desired behavior: libxsmm_berrier_release tracks if barrier was initialized and if not frees only the data allocated in libxsmm_barrier_create

**Comment by alheinecke** [comment]
bad wording in commit message, let's keep this open and discuss the fix

**Comment by hfp** [comment]
I am closing this since this has been discussed and no further issue is know so far. I will look into improvements of the barrier wrt different platforms and µarchs, but that is a different issue.
