### ISSUE TITLE
libxsmm_timer_tick() or libxsmm_timer_duration() return wrong values

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#107]
using libxsmm_timer_tick() instead of gettimeofday() results in substantially different timings. It seems commit https://github.com/hfp/libxsmm/commit/fa200ebdc3bbaeb4a6e64a3e7fcfcd8216c9ac29 caused these problems. rdtsc() doesn't return ticks, it returns nominal ticks. 

Code:
gettimeofday(&l_start, NULL);
ROI();
gettimeofday(&l_end, NULL);

vs.
l_start = libxsmm_timer_tick();
ROI();
l_end = libxsmm_timer_tick();

**Comment by alheinecke** [comment]
It seems this code is not valid, is the ticks are stemming from rdtsc as there is no multiplication with 1/frequency. 

LIBXSMM_API_DEFINITION double libxsmm_timer_duration(unsigned long long tick0, unsigned long long tick1)
{
  const double d = (double)(LIBXSMM_MAX(tick1, tick0) - tick0);
#if defined(_WIN32)
  LARGE_INTEGER frequency;
  QueryPerformanceFrequency(&frequency);
  return d / (double)frequency.QuadPart;
#elif defined(CLOCK_MONOTONIC)
  **return d * 1E-9;**
#else
  **return d * 1E-6;**
#endif
}

**Comment by hfp** [comment]
I’ve reverted the timer change.
