### ISSUE TITLE
libxsmm_dispatch returns 0, standalone generator gives broken code

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#109]
For small matrices with large LDXs the current head doesn't work in default compilation mode as the values which are "int"-types in the frondend are silently down-converted to "short" values, if I debugged the issue which shows up in the pyfr examples correctly. For LDX greater than 65535 this results into NULL pointers (dispatch) or wrong code (standalone generator) as the LDXs wrap around. 
Therefore, the default compilation should use internally int and per flag the "short" route should be enabled.

**Comment by hfp** [comment]
I realize that this is not documented in our reference. However, it is commented here:
https://github.com/hfp/libxsmm/blob/master/Makefile#L85

Regarding the default, I will do some measurements with `make BIG=1` vs. the current default. With this information, we should discuss what might be the default. The option and the default can be then documented.

**Comment by alheinecke** [comment]
Let's look at the performance! However, for three reasons the default is not only performance dependent, I believe:
a) the current way breaks some fundamental assumption (int is silently casted to short, very hard to debug), so it shouldn't be default
b) when BIG=0 then we should generate a different frontend where the corresponding values are shorts, to give a minimal amount of type-checks (people look in headers for function definitions, rather than reading some documentation)
c) int all the way down should be the default for the rpm package

**Comment by alheinecke** [comment]
I measured several samples in smm and was not able to make out a substantial benefit for BIG=0, only for very small sizes there might be 1%-2% when running out of a hot L1 cache, however in real application that should be a memory bound scenario. -> BIG=1 should be default as there is no impact and it's cleaner. For BIG=0 the frontend should be changed to use short instead of int for M,N,K,LDA,LDB,LDC.

**Comment by hfp** [comment]
GCC compiled code shows up to 5% slowdown with BIG=1 vs. BIG=0 when relying on samples/dispatch. So it is perfectly valid to have the more general setting as a default (BIG=1). If we ever re-evaluate vectorizing the call overhead (diff function), we can easily re-evaluate the overhead.
