### ISSUE TITLE
integration tests

### ISSUE THREAD

**Issue by maxhutch** [hfp/libxsmm#11]
Could some of the samples, smm seems particularly suitable, be massaged into integration tests?  It would boost my confidence in making changes and opening PRs.

I use travis for other projects.  If someone else sets up a script that returns 0 on pass and non-zero on fail, I'm willing to set up the rest.

**Comment by alheinecke** [comment]
I requested travis support from Hans earlier this we(I cannot enabled it right now...) exactly for this reason and as we have the JIT being pushed in a couple of days.

For now I suggest to use the test command after make and then grep'ing for diff. We simply need to put this into a bash script and we have our travis test.

**Comment by alheinecke** [comment]
make MNK="2 3, 23" test
grep "diff" samples/cp2k/cp2k-perf.txt | grep -v "diff=0.000"
