### ISSUE TITLE
2 * bad if statements ?

### ISSUE THREAD

**Issue by dcb314** [hfp/libxsmm#110]
1.

libxsmm-1.5.2/src/generator_x86_instructions.c:1647:56: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]

Source code is

    if ( ((int)i_gp_reg_base < LIBXSMM_X86_GP_REG_RAX) &&
         ((int)i_gp_reg_base > LIBXSMM_X86_GP_REG_R15) &&
         /*(i_gp_reg_base < 0) &&*/ (i_gp_reg_base > 15) &&
         ((int)i_gp_reg_base != LIBXSMM_X86_GP_REG_UNDEF) )

2.

libxsmm-1.5.2/src/generator_x86_instructions.c:1655:56: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]

Source code is

    if ( ((int)i_gp_reg_idx  < LIBXSMM_X86_GP_REG_RAX) &&
         ((int)i_gp_reg_idx  > LIBXSMM_X86_GP_REG_R15) &&
         /*(i_gp_reg_idx  < 0) &&*/ (i_gp_reg_idx  > 15) &&
         ((int)i_gp_reg_idx  != LIBXSMM_X86_GP_REG_UNDEF) )

**Comment by alheinecke** [comment]
Thanks. Yeah, there seem to be double checks. Can you please share which compiler and which version is printing the warning such that we can test our fix?

**Comment by dcb314** [comment]
>which compiler and which version

Any version of gcc from the last three years. 
You will also need to use compiler flag -Wlogical-op.
