### ISSUE TITLE
Remove any calls performing non-private file I/O (incl. console output)

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#14]
A library is not supposed to perform I/O operations which is not invisible (console, and leave-behind files). However, our non-NDEBUG code path may perform such kind of I/O to improve application testing and debugging. This requirement belongs to the code quality category which is about allowing our code to be adopted where highest standards apply.

**Comment by hfp** [comment]
libxsmm_build.c completed.

**Comment by alheinecke** [comment]
We have many issue that people don't know what's going on (e.g. MKL fallback is called, NULL is return when requesting a pointer). We should print stderr messages when this happens.

**Comment by hfp** [comment]
Moved this issue to https://github.com/hfp/libxsmm/wiki/Development#longer-term-issues.
