### ISSUE TITLE
Handle hash key collisions in the code cache.

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#15]
This issue is known both in terms of the problem and the solution. It is planned to evict code from the cache in case of a collision in order to avoid the performance overhead of a full collision handling. The latter requires an exact comparison of two descriptors on top of CRC32 based hash key. Moreover, the infrastructure to receive the target/populated descriptor needs to be implemented. Actually evicting the code also requires to properly release/reuse the memory associated with an entry of the cache.

**Comment by hfp** [comment]
There is still some risk of alternating between two kernels which might evict each other. As pointed out, the exact comparison of two descriptors is needed every time, however toggling the highest bit of the pointer found in cache can enter a full collision handling (which is rather quick to check for the fast path). As a further note, our exact comparison of xGEMM descriptors may be accelerated using SIMD instructions with the potential to compare the entire descriptor within one cycle.

**Comment by vondele** [comment]
As an alternative, since the number of descriptors is limited and could be tested exhaustively for a given size (e.g. up to m=n=k=128), pretest for this, and only check if outside this range.

**Comment by hfp** [comment]
That's the way it is currently implemented (and qualified using some separate sandbox code). The cache size is fixed at compile-time using the problem size related to the library's THRESHOLD parameter and a fixed factor. The THRESHOLD is given at build time (default 80**3) and specifies what an SMM is (as opposed to something worth calling BLAS). The aforementioned factor is currently hard-coded (8) and intended to minimize the number of collisions e.g., the entire MNK-space (cubic form) of 80**3 gives just ~0.8% collisions due to the high-quality hash (CRC32).
Unfortunately, even when only looking at the MNK-parameters, we are unlikely able to test in an exhaustive fashion since the THRESHOLD already covers non-cubic problem spaces e.g., M=256, N=9, K=8 where M*N*K is leq. 80**3.

In fact, the whole point of reworking our dispatch was to cover all xGEMM arguments (transa, transb, m, n, k, lda, ldb, ldc, alpha, beta) as well as some additional parameters (double/single precision, aligned_ld, aligned_st, prefetch strategy). The entire parameter space can and will be exercised due to our JIT feature, hence we cannot test in an exhaustive fashion.

**Comment by vondele** [comment]
80^3 is still a small number, alpha and beta are problematic. 

Well, that's the price to pay for being general in that case... of course, it is important that this is fixed, since it is a recipe for wrong results.

**Comment by hfp** [comment]
The case can be considered "fixed" wrt to the actual issue resolution. Any code-tuning will be separate and independent of this issue (overhead quantification under various conditions will be a prerequisite for tuning the code).
