### ISSUE TITLE
Simple example fails

### ISSUE THREAD

**Issue by greensquirrel** [hfp/libxsmm#159]
I am doing my first steps with libxsmm by checking a little matrix vector multiplication.
But it fails:

```  
$ ./xsmm_demo
y[0]: 0.000000
y[1]: 0.000000
y[2]: 0.000000
xsmm_demo: xsmm_demo.cpp:52: int main(): Assertion `1*13 + 2*17 == y[0]' failed.
```

Here is the source code:
```
$ cat xsmm_demo.cpp 
#include <cassert>
#include <cstdio>

#include "libxsmm.h"


int main()
{
    libxsmm_init();

    // 1 2
    // 3 5
    // 7 11
    float mat[3*2];
    mat[0]= 1.0;
    mat[1]= 2.0;
    mat[2]= 3.0;
    mat[3]= 5.0;
    mat[4]= 7.0;
    mat[5]= 11.0;

    // 13
    // 17
    float v[2];
    v[0]= 13;
    v[1]= 17;

    float y[3];
    y[0]= 0;
    y[1]= 0;
    y[2]= 0;

    const float alpha= 1.0;
    const float beta= 0.;

    const libxsmm_blasint m= 3;
    const libxsmm_blasint n= 1;
    const libxsmm_blasint k= 2;

    const libxsmm_blasint lda= 2;
    const libxsmm_blasint ldb= 1;
    const libxsmm_blasint ldc= 1;

    libxsmm_sgemm(0, 0, m, n, k,
      &alpha, mat, &lda, v, &ldb,
      &beta, y, &ldc);

    for (size_t i= 0; i < 3; ++i)
    {
        printf("y[%lu]: %f\n", i, y[i]);
    }
    assert(1*13 + 2*17 == y[0]);
    assert(3*13 + 5*17 == y[1]);
    assert(7*13 + 11*17 == y[2]);

    return 0;
}
```

Where is the problem?

Thank you in advance!

**Comment by alheinecke** [comment]
I think you are using row-major data layout, however, LIBXSMM is BLAS-compatible and therefore col-major. For col-major m<=lda, m<=ldc, k<=ldb holds true. In order to use LIBXSMM for row-major data you need to exchange A and B when passing the arguments, since C^T = B^T * A^T is the same as C = A*B.

**Comment by hfp** [comment]
Alex' explantion hits it, and building and running your code:

```
g++ -I../../include xsmm_demo.cpp /path/to/libxsmm.a -lblas
./a
```
gives for instance:

```
 LIBXSMM ERROR: lda needs to be greater than or equal to m!

 LIBXSMM ERROR: lda needs to be greater than or equal to m!
 (error #90003)
 ** On entry to SGEMM  parameter number  8 had an illegal value
y[0]: 0.000000
y[1]: 0.000000
y[2]: 0.000000
assertion "1*13 + 2*17 == y[0]" failed: file "xsmm_demo.cpp", line 52, function: int main()
Aborted (core dumped)
```

**Comment by hfp** [comment]
Please do not hesitate to open issues that help you to get started. It can be a good exercise for us to improve our material and documentation. There are already some sample codes, which can be perhaps helpful:

* Our "[blas](https://github.com/hfp/libxsmm/blob/master/tests/blas.c#L85)" test case (column 3 and 4) now includes your case (column and row major)
* https://github.com/hfp/libxsmm/tree/master/samples/smm#smm-sample-collection
* https://github.com/hfp/libxsmm/tree/master/samples/xgemm
