### ISSUE TITLE
support for transb in the generator backend

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#18]
Currently the generator can only generate code for non-trans operations. Support for transB is straightforward and should be therefore added.

**Comment by hfp** [comment]
Another (related) work item is to enable TT-kernels in the frontend by leveraging ROW_MAJOR in case of COL_MAJOR (and vice-versa).

**Comment by alheinecke** [comment]
IMHO that doens't work as COL_MAJOR/ROW_MAJOR also changes the layout of C what TT-kernels not supposed to do.

**Comment by hfp** [comment]
Moved this issue to https://github.com/hfp/libxsmm/wiki/Development#longer-term-issues.
