### ISSUE TITLE
run_deepbench.sh crashes out on KNL 

### ISSUE THREAD

**Issue by dmudiger** [hfp/libxsmm#181]
the run command that I use - run_deepbench.sh 1000 1 f32 A L 0
The WU kernels crashes even for the first case

running only FP ( run_deepbench.sh 1000 1 f32 F L 0 ) -
 - correctness fails for PARAMS: W:7  H:7  N:16  C:832  K:256  R:1  S:1  P:7  Q:7  STRIDE:1
 - crash with PARAMS: W:7  H:7  N:16  C:832  K:128  R:5  S:5  P:7  Q:7  STRIDE:1

**Comment by hfp** [comment]
Meanwhile everything was passing on all supported architectures incl. Winograd. However, our most recently merged AVX-512 perf. improvements regressed with Winograd (but this is unrelated and a separate issue).
