### ISSUE TITLE
LIBXSMM ERROR: BGEMM block-size is invalid!

### ISSUE THREAD

**Issue by gnthibault** [hfp/libxsmm#186]
I am trying to integrate libxsmm to a benchmark code, unfortunately, I am encountering a runtime problem when allocating a libxsmm_bgemm_handle with libxsmm_bgemm_handle_create.

LIBXSMM ERROR: BGEMM block-size is invalid!

I was able to write a simple MWE, that i compiled along with latest source code version:
commit 50327f9241feec34e51721409a0989d06b6122f5

```
// STL
#include <cstdlib>
#include <algorithm>
#include <numeric>
#include <iostream>

// BLAS
#include <cblas.h>

// Libxsmm
#include <libxsmm.h>

// Compile using g++ -std=c++11 ./bug.cpp -lxsmm -lxsmmext -lblas -o ./bug
int main( int argc, char* argv[]) {
  libxsmm_init();
  libxsmm_set_verbosity(2);
  const double alpha = 1.0;
  const double beta = 0.0;
  const char TransA = 'N';
  const char TransB = 'N';
  const libxsmm_blasint M = 2;
  const libxsmm_blasint N = 3;
  const libxsmm_blasint K = 2;
  const libxsmm_blasint lda = M;
  double *A = (double*)libxsmm_malloc(lda * K * sizeof(double));
  const libxsmm_blasint ldb = K;
  double *B = (double*)libxsmm_malloc(ldb * N * sizeof(double));
  const libxsmm_blasint ldc = M;
  double *C = (double*)libxsmm_malloc(ldc * N * sizeof(double));
  const libxsmm_gemm_prefetch_type prefetch =  LIBXSMM_PREFETCH_AUTO;
  const libxsmm_gemm_precision precision =
libxsmm_gemm_precision::LIBXSMM_GEMM_PRECISION_F64; 
  libxsmm_bgemm_handle* pHandle = libxsmm_bgemm_handle_create(
    precision,
    M, N, K,
    /* If the block-size (bm, bn, or bk) is not given, a suitable value is
    chosen internally*/
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    &alpha,
    &beta,
    NULL,
    &prefetch,
    NULL);

  if (pHandle) {
    libxsmm_bgemm_omp(pHandle, (const void*)A, (const void*)B, (void*) C, 1);
    libxsmm_bgemm_handle_destroy(pHandle);
  } else {
    std::cout<<"pHandle allocation went wrong"<<std::endl;
  }
  libxsmm_free(A);
  libxsmm_free(B);
  libxsmm_free(C);
  libxsmm_finalize();
  return EXIT_SUCCESS;
}

```

**Comment by hfp** [comment]
Thanks for the report!

We are aware of the limitations. The code is currently under development and comes with various limitations:

1. Alpha, Beta are not taken into account i.e., Alpha=Beta=1 is assumed
2. No transpose is taken into account i.e., atrans=btrans='N' is assumed
3. No remainder tiles are considered

The copy-in and copy-out functions provide leading dimnensions as part of the interface. However, any non-default (non-tight) leading dimension is not taken into account.

In addition, the advertised "automatically chosen" values are eventually invalid (bm=bn=bk=32 right now). The latter in conjunction with point (3) applies to your sample code. Right now, one need to provide blocksizes, which evenly divide the matrix shape (tiling without remainder).

**Comment by hfp** [comment]
You may also look at our complimentary run-scripts (e.g., [perfSweep.sh](https://github.com/hfp/libxsmm/blob/master/samples/bgemm/perfSweep.sh)). You will find that blocksizes are currently manually given (among other parameters) in order to extract the highest performance (which is also specific to the system and the CPU kind).

**Comment by hfp** [comment]
We will generalize BGEMM and thereby BGEMM may share same tiling scheme with our big GEMM. This tiling scheme is currently being reworked.
