### ISSUE TITLE
FORTRAN interface

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#2]
Generate and implement a FORTRAN interface along with some sample code (driver).

**Comment by alheinecke** [comment]
We should build the fortran module automatically

**Comment by alheinecke** [comment]
review kind selection for single and double

**Comment by alheinecke** [comment]
I ran the F90 interface serial in VTune, and the dispatching in clearly slow (there are huge overheads in assembly only routines). Need to debug further.

gfortran (4.8.2, redhat) is not compiling libxsmm.f90.

**Comment by alheinecke** [comment]
A first working version (works with Intel and GNU toolchains) is now available:
https://github.com/hfp/libxsmm/commit/00f09d02e3bfbc8d0410d40ef104a60e5b3dad15
Closing this now.
