### ISSUE TITLE
make install should only copy files if necessary

### ISSUE THREAD

**Issue by jsharpe** [hfp/libxsmm#202]
If the files haven't changed since the last call to make install then they should not be touched in the destination repo.

On a GNU version of cp this can be achieved by using the -u flag. Otherwise rsync --update should be used in the Makefile

**Comment by hfp** [comment]
Thank your for the request!

I have removed this flag quite some time ago because it is not applicable accross our supported platforms. However, I will reintroduce `-u` selectively depending on the platform (OS).

**Comment by hfp** [comment]
Implemented in revision [master-1.8.2-71](https://github.com/hfp/libxsmm/commit/848e0344dfd5f74a84be54e8a47c22b8bf9ca24f), and [successfully tested](https://travis-ci.org/hfp/libxsmm/builds/327232277). The copy-update is not available under OSX (to avoid implementation effort i.e., checking whether rsync is available or not).
