### ISSUE TITLE
make test fails to build samples/cp2k/cp2k.cpp

### ISSUE THREAD

**Issue by rathann** [hfp/libxsmm#204]
```
$ make test STATIC=0 SYM=1 SSE=0 AVX=0 'LDFLAGS=-Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' VERSION_MAJOR=1 VERSION_MINOR=9 PREFIX=/builddir/build/BUILDROOT/libxsmm-1.8.3-1.fc28.x86_64/usr POUTDIR=lib64
[...]
========================
Running CP2K Code Sample
========================
g++ -g -fpic -std=c++11 -Wall -Wno-unused-function -Wno-attributes -O2 -funroll-loops -ftree-vectorize -fdata-sections -ffunction-sections -fopenmp-simd -fopenmp -pthread -DLIBXSMM_OPENMP_SIMD -DNDEBUG -D__BLAS=1 -D__CBLAS -D__OPENBLAS -D__OPENBLAS77 -I/usr/include/openblas -I. -I../../include  -c /builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp -o build/cp2k-cpp.o
g++ -o cp2k build/cp2k-cpp.o    -L/builddir/build/BUILD/libxsmm-1.8.3/lib/ -lxsmm  -Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed -lstdc++ -lgfortran -lm -Wl,--no-as-needed -pthread
build/cp2k-cpp.o: In function `main._omp_fn.2':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:253: undefined reference to `omp_get_num_threads'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:253: undefined reference to `omp_get_thread_num'
build/cp2k-cpp.o: In function `main._omp_fn.0':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:190: undefined reference to `omp_get_num_threads'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:190: undefined reference to `omp_get_thread_num'
build/cp2k-cpp.o: In function `main._omp_fn.3':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:287: undefined reference to `omp_get_num_threads'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:287: undefined reference to `omp_get_thread_num'
build/cp2k-cpp.o: In function `main._omp_fn.5':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:353: undefined reference to `omp_get_num_threads'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:353: undefined reference to `omp_get_thread_num'
build/cp2k-cpp.o: In function `main._omp_fn.4':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:320: undefined reference to `omp_get_num_threads'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:320: undefined reference to `omp_get_thread_num'
build/cp2k-cpp.o: In function `main._omp_fn.1':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:231: undefined reference to `omp_get_num_threads'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:231: undefined reference to `omp_get_thread_num'
build/cp2k-cpp.o: In function `main':
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:190: undefined reference to `GOMP_parallel'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:231: undefined reference to `GOMP_parallel'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:253: undefined reference to `GOMP_parallel'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:287: undefined reference to `GOMP_parallel'
/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:320: undefined reference to `GOMP_parallel'
build/cp2k-cpp.o:/builddir/build/BUILD/libxsmm-1.8.3/samples/cp2k/cp2k.cpp:353: more undefined references to `GOMP_parallel' follow
/builddir/build/BUILD/libxsmm-1.8.3/lib//libxsmm.so: undefined reference to `dgemm_'
/builddir/build/BUILD/libxsmm-1.8.3/lib//libxsmm.so: undefined reference to `dlerror'
/builddir/build/BUILD/libxsmm-1.8.3/lib//libxsmm.so: undefined reference to `dlsym'
/builddir/build/BUILD/libxsmm-1.8.3/lib//libxsmm.so: undefined reference to `sgemm_'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:67: cp2k] Error 1
make: *** [Makefile:1269: samples/cp2k/cp2k-test.txt] Error 2
$ 
```

Any clues?

**Comment by rathann** [comment]
It looks like it's not getting linked against `-ldl` and `-lopenblas` (or maybe `-lopenblaso`).

**Comment by hfp** [comment]
I think this is because of injecting your LDFLAGS, which prevents Makefile.inc to add the necessary dependences. I will do two things:

* I will add the hardening flags upfront (`-Wl,-z,relro`).
* You can use ELDFLAGS to inject your stuff.

The library uses SSE4 as baseline for the statically compiled code, if you apply "SSE=0 AVX=0" makes not much sense (but causes just overhead or unnecessary CPUID-dispatch). As a note, you cannot make anything more viable or more conforming according to the packing policy since functions can be decorated for different targets (independent of compiler flags; that's used by LIBXSMM) plus someone could use inline assembly (that's also used in LIBXSMM). Any CPU prior to SSE4 is very likely older than a decade and it is extremely unlikely that owner wants to use LIBXSMM (it's meant for scientific computing).

**Comment by hfp** [comment]
Unrelated to issue (but related to your compile line): the following keys are now suported VERSION_MAJOR, VERSION_MINOR, VERSION_UPDATE, VERSION_API (the latter two are new). This was part of the "soname rework". The behavior is to create a fully versioned SO (e.g., `libxsmm.so.1.8.3`), and to create two symlinks: (1) `libxsmm.so` -> `libxsmm.so.1.8.3`, and (2) `libxsmm.so.1.8` -> `libxsmm.so.1.8.3`. The "1.8" for the second case stems from `VERSION_API`, which is MAJOR.MINOR by default.

**Comment by rathann** [comment]
If I move our LDFLAGS to ELDFLAGS, I get this:
```
+ make test PYTHON=/usr/bin/python2 STATIC=0 SYM=1 SSE=0 AVX=0 'ELDFLAGS=-Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' PREFIX=/builddir/build/BUILDROOT/libxsmm-1.8.3-1.fc28.x86_64/usr POUTDIR=lib64
========================
Running CP2K Code Sample
========================
make: invalid option -- 'c'
make: invalid option -- '='
make: invalid option -- '/'
make: invalid option -- 'u'
make: invalid option -- '/'
Usage: make [options] [target] ...
Options:
...
# command line
ELDFLAGS = -Wl,-z,relro

```
It looks like a quoting issue.

**Comment by rathann** [comment]
If you use `VERSION_MAJOR.VERSION_MINOR` as `VERSION_API`, which gets embedded in `SONAME` (`libxsmm.so.1.8`, for example) then every `VERSION_MINOR` increase creates an ABI-incompatible library. I'm not sure that's intended. The most common scheme is to use only `VERSION_MAJOR` in `SONAME`. Indeed, using `VERSION_API=1` does give the expected `SONAME` of `libxsmm.so.1`.

On the other hand, 1.8.3 is not compatible with 1.8 because there are quite a few public symbols removed, so it might make sense to bump `VERSION_MAJOR` to 2 anyway.

**Comment by hfp** [comment]
I will look into the quoting issue!  Let's get through with this and make our next release compliant with your needs/recommendations.

For binary compatibility, we have only a [weak commitment](https://github.com/hfp/libxsmm/wiki/Q&A#is-libxsmm-compatible-from-version-to-version-or-what-is-the-abi-commitment) i.e., it's not enforced/tested. However, saying **there are quite a few public symbols removed** is likely caused by our internal API (which is not decorated with `visibility(hidden)`).

I think our public interface is very stable (except for the DNN domain). For instance, LIBXSMM is compatible (with no change in CP2K) since CP2K 3.0, similar statements hold for PyFR, EDGE, NekBox, and other applications. ( I still consider to decorate our internal API in a future release. )

**Comment by rathann** [comment]
Thank you! Let me open another issue with ABI differences report. If none of the removed symbols are public then perhaps we should keep the `SONAME`s at `.so.1` in our package, then.

**Comment by loveshack** [comment]
Please talk to me about the Fedora package; I've been through these things, even if I have got them wrong. However, I'm confused about the problem with the existing check stanza as it failed for me with the same make flags as for the build as far as I could tell, but I hadn't found time to debug it.
(I'm inclined to try changing the rpm packaging to assume sse4.2, despite out magny cours, but that's  a Fedora issue.)

**Comment by hfp** [comment]
Hmm, just realized that what you refer as "Magny Cours" introduced SSE 4.2 with the "Bulldozer" generation (the first Opteron variant with SSE 4.2 seems to be codenamed "Zurich"). I will double-check if I can relax to SSE3+CRC32 (that's what I really only want as a baseline).

**Comment by loveshack** [comment]
You wrote: 

> Hmm, just realized that what you refer as "Magny Cours" introduced SSE
> 4.2 with the "Bulldozer" generation (the first Opteron variant with
> SSE 4.2 seems to be codenamed "Zurich"). I will double-check if I can
> relax to SSE3+CRC32 (that's what I really only want as a baseline).

No; Magny-Cours isn't Bulldozer (which has sse4.2 and avx/fma)
<https://en.wikipedia.org/wiki/List_of_AMD_Opteron_microprocessors)>.
Magny Cours has

```
$ cpuid -1|grep SSE
      SSE extensions                         = true
      SSE2 extensions                        = true
      PNI/SSE3: Prescott New Instructions     = true
      SSSE3 extensions                        = false
      SSE4.1 extensions                       = false
      SSE4.2 extensions                       = false
      SSE extensions                        = true
      SSE4A support                          = true
      misaligned SSE mode                    = true
      SSSE3/SSE5 opcode set disable = false
      128-bit SSE executed full-width = true
```

I don't know what crc32 comes under -- cpuid doesn't show it as such --
but I think you said PNI was enough previously.  (32-core Magny-Cours
nodes might still be reasonable for, say, cp2k in the
allotallv-dominated regime, but are definitely "legacy".)

SSE3 support wouldn't solve the issue of Fedora demanding packages
support base amd64, if it really does, but I don't think that's your
problem.

**Comment by hfp** [comment]
Thanks for the information! CRC32 is part of the SSE4.2 feature bits.

Now that SSE3 is used (master), I can lower the baseline further (and still do CPUID-dispatch for the critical path). Just let me know what you can take, and I will implement it accordingly! I want to make our defaults according to your needs rather than you change to "something" out of our control (and regular tests).

Here is what I can do (let me know your preferences):

* Remove the target flags entirely for shared library builds i.e., SSE2 aka 64-bit ABI is used. Ideally we can keep SSE3 as a flag (and you can take it), but if your can't I will remove it.
* Our next release will be able to JIT-generate SSE3 code. Previously, LIBXSMM only generated code for AVX (and beyond). Your legacy system actually never got anything out of LIBXSMM.

The last point should significantly improve performance for your anticipated legacy system.

**Comment by hfp** [comment]
> 'ELDFLAGS=-Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'

I checked with ELDFLAGS="-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" as well as with your kind of quoting the ELDFLAGS, and both worked for me. Anyhow, the current master and the upcoming release (v1.9) will harden the build by default. If you still have `hardening-check` installed, you can check this once your prepare v1.9.

**Comment by loveshack** [comment]
You wrote: 

>> 'ELDFLAGS=-Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
>
> I checked with ELDFLAGS="-Wl,-z,relro
> -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" as well as with your
> kind of quoting the ELDFLAGS, and both worked for me. Anyhow, the
> current master and the upcoming release (v1.9) will harden the build
> by default. If you still have `hardening-check` installed, you can
> check this once your prepare v1.9.

For what it's worth, I pushed an rpm build without the hardening flags,
as I can't think libxsmm provides much attack surface and it can wait
for the next release.  Thanks for the change anyhow, and I should have
said thanks for going to the trouble of providing sse3 support, though I
think it's really Fedora's job to cope with that things which are
micro-architecture-specific.

**Comment by hfp** [comment]
Version 1.9 arrived!

You're perhaps right, the exposure should be low given what LIBXSMM is about. Nevertheless, I have included reasonable hardening measures by default (goal: no performance impact). Now, building with `make STATIC=0` yields (`hardening-check lib/libxsmm.so`):

```bash
lib/libxsmm.so:
 Position Independent Executable: no, regular shared library (ignored)
 Stack protected: no, not found!
 Fortify Source functions: no, only unprotected functions found!
 Read-only relocations: yes
 Immediate binding: yes
```

When built with `make STATIC=0 HARDEN=1`, it even yields `Stack protected: yes`:

```bash
lib/libxsmm.so:
 Position Independent Executable: no, regular shared library (ignored)
 Stack protected: yes
 Fortify Source functions: no, only unprotected functions found!
 Read-only relocations: yes
 Immediate binding: yes
```

However, protecting the stack has performance impact for stack-local data accesses (arrays). Therefore even detecting the "maintainer build" (STATIC=0, GCC tool chain) omits stack protection (aka HARDEN=1). As promised, detecting the "maintainer build" does not apply target flags and looks like (`<compiler default>`):

```bash
===========================================================
LIBXSMM release-1.9
-----------------------------------------------------------
GNU Compiler Collection: cc 6.3.0, g++ 6.3.0, and f77 6.3.0
C / C++ target: <compiler default>
Fortran target: <compiler default>
-----------------------------------------------------------
```

I hope detecting the maintainer build allows for (almost) zero adjustments on your side. Also, runtime code-emission (JIT) targeting SSE3 is an entirely new feature in v1.9 which can improve performance for legacy hardware (happy 32-core Magny-Cours nodes ;-).

**Comment by loveshack** [comment]
Thanks.  I'll try to do an updated rpm build next week, unless Dominik
wants to look at it in the meantime.
