### ISSUE TITLE
Low precision gemm does not work for several cases

### ISSUE THREAD

**Issue by natarajj** [hfp/libxsmm#206]
The function libxsmm_wmmdispatch, throws error for several M,N,Ks (e.g., 40,30,25) and some of the prefetching strategies do not work too.

**Comment by alheinecke** [comment]
Can you please more specific what doesn't work. E.g. there limitations like needs to fulfill K%8=0. Also specifics on the prefetching strategies are needed.

**Comment by alheinecke** [comment]
This was fixed in 596958db325a06dfd5040b86dac18b2fd728469d
