### ISSUE TITLE
enhance Xeon (not Xeon Phi) convolution performance by adding finer grain control for streaming stores

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#208]
Following can result into slightly better performance on Xeon (not Xeon Phi) CPUs:

[egeorgan@pcl-tiergarten libxsmm]$ git diff
diff --git a/src/generator_convolution_common.c b/src/generator_convolution_common.c
index 4699b7d..b930a4b 100644
--- a/src/generator_convolution_common.c
+++ b/src/generator_convolution_common.c
@@ -490,7 +490,7 @@ void libxsmm_generator_convolution_forward_store_output( libxsmm_generated_code*
   }
 
   /* if requested let's switch to streaming stores */
-  if ( i_conv_desc->use_nts == 1 ) {
+  if ( i_conv_desc->use_nts == 1 && (i_conv_kernel_config->instruction_set == LIBXSMM_X86_AVX512_KNM) ) {
     l_intr_store = LIBXSMM_X86_INSTR_VMOVNTPS;
   }
 
diff --git a/src/libxsmm_dnn_handle.c b/src/libxsmm_dnn_handle.c
index 9c6b37a..f680d2c 100644
--- a/src/libxsmm_dnn_handle.c
+++ b/src/libxsmm_dnn_handle.c
@@ -477,9 +477,9 @@ LIBXSMM_API_INTERN libxsmm_dnn_err_t libxsmm_dnn_internal_create_conv_handle_dir
       handle->use_nts_bwd = 0;
     }
 
-    if ((libxsmm_target_archid == LIBXSMM_X86_AVX512_CORE || libxsmm_target_archid == LIBXSMM_X86_AVX512_ICL) && handle->desc.K/16 <= 8) {
+    /*if ((libxsmm_target_archid == LIBXSMM_X86_AVX512_CORE || libxsmm_target_archid == LIBXSMM_X86_AVX512_ICL) && handle->desc.K/16 <= 8) {
       handle->use_nts_bwd = 0;
-    }
+    }*/

**Comment by hfp** [comment]
Is this issue still current or shall I put this to our list of (closed) [longer term issues](https://github.com/hfp/libxsmm/wiki/Development#longer-term-issues)?

**Comment by alheinecke** [comment]
That will be fixed with the currently developed new convolution variants.
