### ISSUE TITLE
Allow LIBXSMM_MAX_STATIC_TARGET_ARCH to be overridden

### ISSUE THREAD

**Issue by atdt** [hfp/libxsmm#212]
I'd like to be able to set `LIBXSMM_MAX_STATIC_TARGET_ARCH` to `LIBXSMM_X86_AVX2`, to prevent the use of AVX-512 in a shared environment that is sensitive to AVX-512's Turbo curve impact, and (crucially) to avoid the CPUID-based indirect call. Could libxsmm honor pre-existing definitions of `LIBXSMM_MAX_STATIC_TARGET_ARCH`, or allow its value to be overridden by means of some other symbol that is supplied by the user at compile time?

**Comment by hfp** [comment]
**Just for the record** (as you likely know): the `LIBXSMM_TARGET` environment variable (or equivalent API) can be used to limit such kind of code to a certain target. For example, `LIBXSMM_TARGET=avx2` (or `LIBXSMM_TARGET=hsw`) can be used to force AVX2 instructions even if AVX-512 capabilities are present. However, this may not avoid the indirect function call.

**Questions**

* Are you planning to apply this only to a certain function domain e.g., the SpMdM domain?  
  Asked different: do you want to run say MMs with AVX-512 but SpMdM with AVX2 only?
* Regarding Turbo curve impact, what processor SKU are you focused on?  
  I could CPUID-limit SpMdM to AVX2 for SKX (but perhaps not for CLX).

**Comment by hfp** [comment]
Do you have some input for the above questions?

**Comment by atdt** [comment]
Thanks for the reply. Yes, I was hoping to avoid the indirect function call.
Not planning to apply this selectively to a certain function domain, and focusing on SKX.

**Comment by hfp** [comment]
If you use below make-line, you can probably get what you want with your version of LIBXSMM already.

```bash
make AVX=2 INTRINSICS=1
```

In the above case, none of the functions are decorated with target flags, and the static target flags will rule.

I am keeping this issue open to allow limiting the target decoration to specific flags, but you are probably served by the above already. However, the above example produces a library, which can only run on systems with at least AVX2. On the other hand, you also get rid of dynamic dispatch for target-decorated functions. Of course, JIT code is always dispatched according to the CPUID unless the `LIBXSMM_TARGET` environment variable is used.

**Comment by hfp** [comment]
To avoid an indirect function call ```make AVX=2 INTRINSICS=1``` is the right way in generall i.e., `INTRINSICS=1` is key to avoid indirectly going beyond the specified static code path (e.g., `AVX=2`). Commit 1f0de08 adjusts the SpMDM domain and it now enters the AVX2 code-path without an indirect function call.
