### ISSUE TITLE
possible problem with gcc 8.1.1

### ISSUE THREAD

**Issue by loveshack** [hfp/libxsmm#228]
I've been trying to rebuild the Fedora rpm on the bleeding edge ("rawhide"), and have got to the stage of the cp2k example that it uses as a test failing with a numerical error.  I assume the regression is something to do with it using gcc 8.1.1, though that's not clear.  (I think it was built with a pre-release 8.0 previously.) Do you happen to know of any problem for libxsmm with 8.1 (especially fixed since libxsmm1.9), or general success with it?

No worries if not, but I thought I'd ask before trying to diagnose the problem.

[It probably doesn't help, but the build log (with no warnings from -Wall) is at https://kojipkgs.fedoraproject.org//work/tasks/4393/27984393/build.log]

**Comment by hfp** [comment]
> Do you happen to know of any problem for libxsmm with 8.1 (especially fixed since libxsmm1.9), or general success with it?

I havent (yet) started to build release notes for v2.0, but we accumulated ~1107 changes since v1.9 excluding 100s of changes in at least one (internal) development branch.

What I can see with v1.9 is: it compiles fine with GCC 8.1. The failure as shown in the log is according to an exceeded error margin for the CP2K code sample. First this is not CP2K (but some code used in the past to model CP2K/DBCSR's SMM hotspot); it is called "CP2K" for historic reasons since LIBXSMM works with CP2K since CP2K 3.0 and there is no need to rely on a proxy. It is unlikeky due to an issue in OpenMP. It might be an issue with OpenBLAS. For instance on systems with high core count, I found OpenBLAS standard builds for most distributions are hard-coding a limit for the core count (which is badly triggered on SKX with higher count).

Perhaps worth to check:

* Check single-threaded just to make sure.
* Check LIBXSMM/master.

In case the latter plays out, I can help with getting v1.9.1 (our v2.0 is still a bit out).

**Comment by hfp** [comment]
I may get an image up with the bleeding edge "rawhide" and try to reproduce this. Do you know which packages I should install to get a "maintainer system" (aka su loveshack)?

( Since there is no competition between Open Source [no], I recently added some support for Debian `make deb`, which perhaps just leverages lessons learned from RPM based distros/you. ;-)

**Comment by loveshack** [comment]
Thanks for the suggestions, as always.  I'll have to try to figure out
which of the changed packages has caused the regression, which is going
to be a pain.  (I realize it's a cp2k proxy, which seemed the most
appropriate quick sanity test, as I think cp2k is the only Fedora
package that currently depends on libxsmm.)

Obviously I'll report if it is something directly relevant to libxsmm.
You could close this, or I can add what I find out, but problems in
rawhide aren't necessarily relevant to anything else.

**Comment by hfp** [comment]
I got a Fedora/rawhide up, and I have fixed the LIBXSMM/master to avoid a compiler warning (new with GCC 8.1.1), and I added some (simple) bootstrap for Python as I realized that Rawhide not only comes with Python3, but does not provide a symlink called "python" (which renders `#!/usr/bin/env python` somewhat useless).

**Comment by hfp** [comment]
Btw, I could not reproduce this validation error although I used the same flags as shown in the lock. However, I did not run per mock but rather used the normal make process. On the other hand parallelism was very limited in my vbox so perhaps it did not trigger.

( I used vagrant/virtualbox and pulled "bento/fedora-28", which I updated to today's Rawhide. )

**Comment by loveshack** [comment]
You wrote: 

> I may get an image up with the bleeding edge "rawhide" and try to
> reproduce this. Do you know which packages I should install to get a
> "maintainer system" (aka su loveshack)?

I've managed (with a struggle) to get a rawhide Vagrant image going, so
I can at least try to find whatever package has caused the regression,
and you probably have more useful things to do.

If you do want to try, to build from the source rpm
https://kojipkgs.fedoraproject.org//packages/libxsmm/1.9/1.fc29/src/libxsmm-1.9-1.fc29.src.rpm
you basically need the rpm-build package and the package buildrequires:
python, gcc-c++, gcc-gfortran, openblas-devel.  I think the package
maintainer meta-package is fedora-packager, but you don't need that.

> ( Since there is no competition between Open Source [no], I recently
> added some support for Debian `make deb`, which perhaps just leverages
> lessons learned from RPM based distros/you. ;-)

I've a nasty feeling I may have offered to do that and forgotten about
it, but I'm not a developer who could get it into Debian.  (Yes, I'll
look at other packaging as a clue if it doesn't look straightforward.)

**Comment by loveshack** [comment]
You wrote: 

> I got a Fedora/rawhide up, and I have fixed the LIBXSMM/master to
> avoid a compiler warning (new with GCC 8.1.1), and I added some
> (simple) bootstrap for Python as I realized that Rawhide not only
> comes with Python3, but does not provide a symlink called "python"
> (which renders `#!/usr/bin/env python` somewhat useless).

The prohibition on /usr/bin/python was why I was rebuilding the package
(which threw up a binutils bug previously) but I didn't think it had
been removed yet.  I was just sed'ing the Python scripts for that, but
will check and use what you've done if it's merge-able.  (The python
change causes trouble all over the place, of course.)  I'm puzzled by
the warning I didn't see in the build -- I'll check.

**Comment by loveshack** [comment]
You wrote: 

> Btw, I could not reproduce this validation error although I used the
> same flags as shown in the lock. However, I did not run per mock but
> rather used the normal make process. On the other hand parallelism was
> very limited in my vbox so perhaps it did not trigger.

Interesting, thanks.  I can experiment with parallelism in the build
system.  I'd have done the same when I had time.

> ( I used vagrant/virtualbox and pulled "bento/fedora-28", which I
> updated to today's Rawhide. )

I think I must have struggled before that was available, but you're
obviously better than a Fedora maintainer -- no surprise!  (Actually a
maintainer who doesn't use Fedora, only RHEL/CentOS...)

Thanks again.  I'll let you know what I find, probably tomorrow.

**Comment by hfp** [comment]
Btw, you can do something like `make PIC=PIC` (the default is PIC=pic).

**Comment by loveshack** [comment]
I'm using the default -fpic, but I think that's equivalent to -fPIC on x86_64.

Anyhow, your suggestion was spot on.  Running with OMP_NUM_THREADS=1 or 2 in the Fedora build system fixes the check, so I guess an openblas bug report is in order. Many thanks!

**Comment by hfp** [comment]
It can still be the OpenMP implementation of your revision of GCC "8.1.1" for two reasons: it is dynamically loaded by OpenBLAS (if your OpenBLAS is the one with OMP runtime), but also the CP2K sample/proxy uses OpenMP. The latter can be disabled. This can be best achieved by editing samples/cp2k/Makefile: set OMP=0).

**Comment by loveshack** [comment]
The problem is at the openblas level.  It seems more likely to be in OB
itself than libgomp, and I think it's appropriate to raise against OB
initially.
