### ISSUE TITLE
-Wl,--no-as-needed / -Wl,--as-needed aren't needed

### ISSUE THREAD

**Issue by yurivict** [hfp/libxsmm#255]
These flags aren't needed.
They are only ever needed in cases when some library isn't strictly required and could be side-loaded in some way. In most cases, including libxsmm, these flags shouldn't be used.
If you have a missing symbols problem you need to fix it by providing a complete set of libraries. But on FreeBSD I am able to build it fine without these flags.

**Comment by hfp** [comment]
Introduced ASNEEDED build-key, if (0) all dependencies are linked as specified for the target, or if (1) attempt to avoid dependencies if not referenced. Per Makefile.inc, all targets including LIBXSMMM itself were previously treated equally. This patch changes the behavior for LIBXSMM's libraries such that no attempts are made to avoid dependencies that are not referenced. Building sample code "examples" (by using Makefile.inc) however continues to "link as needed".

**Comment by hfp** [comment]
Commit e6f58b3 shows that the linker instructions had some impact (proof before/after: "ldd lib/libxsmm.so"), and the commit removes the unnecessary dependency to libstdc++ (note this is related to sharing a somewhat generic `Makefile.inc` between the LIBXSMM libraries and all the sample codes).
