### ISSUE TITLE
Please add build variables BUILD_SAMPLES and INSTALL_SAMPLES

### ISSUE THREAD

**Issue by yurivict** [hfp/libxsmm#256]
Currently it always builds them, but doesn't install them. This might waste the CPU time for people who only need the library.

Makefile should have
```
BUILD_SAMPLES ?= 0
INSTALL_SAMPLES ?= 0
```
or perhaps just the first one.

**Comment by hfp** [comment]
> Currently it always builds them, but doesn't install them. This might waste the CPU time [...]

I guess, you refer to the "all" target i.e., `make all`?

Do you intend to produce/maintain a FreeBSD package of LIBXSMM?
If so, that's great!

The regular `make` does not build the samples. I can see that you probably use some packaging tool which (magically) invokes some "standard" Make-targets (and assumes certain behavior). I can adjust what happens for our `make all` and `make install`. Though we already have targets that include building and installing the sample code.

On the other hand, I intentionally did not include the samples into the "default" and "install" targets. Do you really want to prebuild and install the samples along with the package?

**Comment by yurivict** [comment]
> Do you intend to produce/maintain a FreeBSD package of LIBXSMM?
> If so, that's great!

I've created the port a few days ago: https://www.freshports.org/math/libxsmm/

I patched Makefile:
```
-all: libxsmm samples
+all: libxsmm
 ```
and
```
-install-all: install samples
+install-all: install
```

So if you could allow user to avoid samples with a variables, or targets, that would be great.

> Do you really want to prebuild and install the samples along with the package?

No, this isn't usually done.
