### ISSUE TITLE
assumed-size F90 interface

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#26]
Currently LIBXSMM's F90 interface requires 2D Fortran arrays as inputs. We have seen applications which need to call LIBXSMM routines for contiguous slices of higher dimensional arrays. A quick test unveiled that the needed reshape is not replaced by a no-op. Therefore, the only solution is to changes LIBXSMM's F90 interface to an assumed-size interface. This will disable row-major support for Fortran.

**Comment by hfp** [comment]
We've moved to assumed shape where possible, however introducing it for the remaining cases is rendering our generic Fortran interface useless: http://stackoverflow.com/questions/24287436/how-to-have-generic-subroutine-to-work-in-fortran-with-assumed-size-array (which appears to be our problem as well).

**Comment by hfp** [comment]
This issue is now addressed by more carefully selecting the procedure for generic interfaces. We allow assumed shape arrays for functions outside of the generic interface (module procedure), or supply those signatures in addition to those procedures which are part of a generic interface.
