### ISSUE TITLE
Extensive changes in the headers require SONAME change on sharwed libraries

### ISSUE THREAD

**Issue by yurivict** [hfp/libxsmm#282]
Headers were significantly changed in 1.10, but SONAME of libs was left the same.

**Comment by hfp** [comment]
Yes, that's true. However for our stable core functionality we stay compatible even on a binary basis. The stable core is all about (small) matrix multiplication.

**Comment by hfp** [comment]
Proper soname increment may be a post v2.0 item. However, I will introduce ABI checks and subsequently release (starting with our next release v1.10.1 or v1.11).

**Comment by hfp** [comment]
We consider LIBXSMM's API for Small Matrix Multiplications (SMMs) as stable, and there was no change that broke compatiblity. All major applications that are known to use this library rely on the SMM domain (CP2K, EDGE, NEK5K, and SeisSol), or were able (and want) to deal with an approved API for other domains such as DL. Until at least v2.0, LIBXSMM is not able to track or even maintain binary compatiblity and hence the SONAME goes with the semantic version. However, a [list of all public functions](https://github.com/hfp/libxsmm/blob/master/.abi.txt) has been implemented (although there is no distinction for some of the functions that are only meant for communication between LIBXSMM and LIBXSMM/ext).
