### ISSUE TITLE
build/install confusion with PREFIX etc.

### ISSUE THREAD

**Issue by loveshack** [hfp/libxsmm#288]
I don't know whether this should be fixed in the Makefile or the instructions, but the .pc files may be incorrect if you just follow the instructions.

I'm using DESTDIR (which I think needs adding to the instructions), PREFIX, and POUTDIR for packaging.  The instructions suggest they only need specifying for "make install"; however, the .pc files are generated by the build stage, not install, so those variables need to be supplied at build time for the .pc files to be correct.

(Thanks for adding DESTDIR, which I should probably have requested.)

**Comment by hfp** [comment]
With the today's master revision, I have tested the following:

```
make PREFIX=$HOME/xsmm-prfxabs install
make PREFIX=../xsmm-prfxrel install
make DESTDIR=$HOME/xsmm-ddirabs install
make DESTDIR=../xsmm-ddirrel install
```

and found `PREFIX` and `DESTDIR` are equal (as expected). I will document this; thank you for the note! However (as you point out), the "prefix" inside of the `.pc` files is not updated accordingly. I will fix this!
