### ISSUE TITLE
sparse conv support

### ISSUE THREAD

**Issue by liuchangready** [hfp/libxsmm#294]
hi，now I can see the libxsmm support the sprase matrix multiply dense matrix 。When can we get the sparse conv kernel。I see the libxsmm_sconvfunction function，but it's a little different from the libxsmm_xmmfunction function，It's too hard for me to finish the sparse conv kernel.can anyone supply some help?thks.

**Comment by alheinecke** [comment]
We are not planning right now for implementing a sparse convolution kernel. libxsmm_sconvfunction is a dense small convolution kernel: R*S*(16)C*16(K). We can also bring more C inside. The kernel assumes following memory layout: [N][Cblock][H][W][16], [N][Kblock][P][Q][16], [Kblock][Cblock][R][S][16][16].

details can be found here: https://arxiv.org/abs/1808.05567

**Comment by hfp** [comment]
Please feel free to open an issue if further assistence is needed.
