### ISSUE TITLE
LIBXSMM DNN Error: Unsupported architecture in case of legacy compiler

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#297]
Some of our intrinsic based code paths are incorrectly dispatched if the code was compiled with an insufficient compiler (e.g., GCC 4.8). Everything works as expected with ICC (or newer/sufficient GCC).

```bash
make -j
cd samples/deeplearning/cnnlayer; make -j
./run_resnet50.sh 56 1000 -1 f32 F L 0
```

Above command shows `LIBXSMM DNN Error: Unsupported architecture!` in case of an insufficient compiler (see above).

**Comment by hfp** [comment]
The error code is assigned at `libxsmm_dnn_convolution_forward.c:64`. However, this code path is likely entered due to an invalid handle setup.

**Comment by alheinecke** [comment]
No, this code path is entered if no AVX512 target is provided by the compiler, however the cpuid check confirmed that AVX512 is there. 

https://github.com/hfp/libxsmm/blob/master/src/libxsmm_dnn_handle.c#L92

This check can only happen, if the used compiler has sufficient AVX512 support. If the compiler has no AVX512 support a platform with AVX512 support needs to be treated as non-AVX512. 

-> This if needs to be guarded by compiler versions support AVX512

**Comment by alheinecke** [comment]
It's not guarded at all. If a compiler doesn't have AVX512 support, then we the if mentioned above needs to be #ifdef away. When we have such a preprocessor macro, then it's 1min fix.

**Comment by hfp** [comment]
The issue is still current (and will be resolved once the DL domain is reimplemented).

**Comment by hfp** [comment]
Fixed in a separate branch (to be merged asap).
