### ISSUE TITLE
fortran module breaks under `-r8` or `-fdefault-real-8`

### ISSUE THREAD

**Issue by maxhutch** [hfp/libxsmm#3]
ifort's `-r8` and gfortran's `-fdefault-real-8` cause LIBXSMM_SINGLE_PRECISION and LIBXSMM_DOUBLE_PRECISION to be the same, causing double implementations of all the calls that differ only in precision.  I can think of a few solutions:
  1. Don't change anything; codes shouldn't be using `-r8` anyways.
  1. Define LIBXSMM_SINGLE_PRECISION using `selected_real_kind`
  1. Define LIBXSMM_SINGLE_PRECISION as `4`
If BLAS had a true interface, then I'd go with (1), but seeing as LIBXSMM_SINGLE_PRECISION being defined as anything other than `4` would break the underlying SGEMM call, I think (2) and (3) are more flexible for right now.  The difference there should be mostly aesthetic.  Thoughts?

**Comment by maxhutch** [comment]
@hfp I've done (2) or (3) in my local copy.  If you want to go that route, I'll open a PR.

**Comment by maxhutch** [comment]
#7 took the (3) approach, which is definitely the simplest.  Close if you think that is adequate.

**Comment by alheinecke** [comment]
yes. let me close this for now and I'll update the whole F90 interface issue we have open.

**Comment by hfp** [comment]
Perhaps we need to introduce an ILP64/LP64 build option if this is something people will need frequently.

**Comment by maxhutch** [comment]
I think `-r8` is ugly and wrong, but it is absolutely necessary for Nek5000 and other implicitly typed fortran programs, of which there are many.  I could probably compile NekBox without it, with a little effort.  You could also go the FFTW route and offer different 'legacy' and 'modern' fortran interfaces.

**Comment by hfp** [comment]
For the REAL I am planning to settle the following:
LIBXSMM_SINGLE_PRECISION = SELECTED_REAL_KIND(6, 30)
LIBXSMM_DOUBLE_PRECISION = SELECTED_REAL_KIND(14, 200)

For LIBXSMM_INTEGER_TYPE, I will adjust wrt LP64 (32-bit) or ILP64 (64-bit).

**Comment by hfp** [comment]
The problem with the current KIND of our REAL types can be shown using the NAG compiler (KIND(1): single, and KIND(2): double precision).

**Comment by alheinecke** [comment]
Are you sure this matches IEEE754? The number are quite a bit off. This would be perfect IEEE754:

LIBXSMM_SINGLE_PRECISION = SELECTED_REAL_KIND(7.22, 38.24)
LIBXSMM_DOUBLE_PRECISION = SELECTED_REAL_KIND(15.95, 307.95)

This is what says (http://fortranwiki.org/fortran/show/Real+precision) which is closer to IEEE, but still sp looks weird:
integer, parameter :: sp = selected_real_kind(6, 37)
integer, parameter :: dp = selected_real_kind(15, 307)
integer, parameter :: qp = selected_real_kind(33, 4931)

**Comment by hfp** [comment]
Let's adopt proven code: https://github.com/cp2k/cp2k/blob/intel/cp2k/src/base/kinds.F#L31

**Comment by alheinecke** [comment]
Can you create a bit-wise comparison example. I experimented in the past with the gnulibs and you can get what ever you want. This definition clearly differs from IEEE754 as we call assembly and C we rely on IEEE754 and have to make sure that we are not getting some gnu internal representation.

**Comment by hfp** [comment]
Commit 4e58958b50eb779620704e0c8d9b7efbf80a2243 removes any LIBXSMM-induced KIND for REAL types while keeping the MODULE PROCEDURE overloads intact (distinction relies on C_FLOAT vs. C_DOUBLE providing a fixed type-width). I've checked the NEK sample collection using "-fdefault-real-8 -fdefault-double-8", and it worked. Therefore this issues will be closed again. Any future compatibility requirement e.g., Fortran 77 conformance will be covered in a new issue.
