### ISSUE TITLE
library might be in limbo state after updating an older copy

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#326]
Let's assuming following scenario: a user occasionally update the LIBXSMM source tree via "git pull". That means the following is happening "git pull && make", then 4 months nothing and then again "git pull && make". I have received over the last month to reports that features (which changed the frontend) are not available in the new build. A "make realclean && make" seems to fix the problem.

**Comment by hfp** [comment]
I will try once more for reproducing the issue over the course of the next days (before closing this issue). However, I committed 73a9eb6 which may already resolve the problem.

**Comment by hfp** [comment]
Closing for now as there was some action taken. If it occurs again, a reproducer would be great.
