### ISSUE TITLE
Test 'malloc' failed

### ISSUE THREAD

**Issue by antoscha** [hfp/libxsmm#340]
LIBXSMM was built with default parameters by running `make && make tests` on Nehalem- and Haswell-based computers. GCC 9.1.0, OpenBLAS 0.3.6.
```
5 of 13 (malloc)... FAILED(1)
```
Other tests are OK.

**Comment by hfp** [comment]
I will take this at begin of August.

**Comment by hfp** [comment]
It seems to be reproducible also with older compilers. At least one "root cause" I found so far is `OMP_PROC_BIND=TRUE`, which is set inside `tests/test.sh` (which is used by `make tests`). Regarding `malloc` there is nothing about OpenMP. I will further investigate.

**Comment by hfp** [comment]
Hello Antoscha, would you be willing to test the master revision and confirm that the issue is resolved?

**Comment by antoscha** [comment]
Good evening,

I will test your patch with pleasure tomorrow. Thank you!

**Comment by antoscha** [comment]
It works!

**Comment by hfp** [comment]
Thank you for checking the patch! This failure btw does not effect any user (`malloc` test was extended checking some new functionality which is not rolled out yet). I will prepare 1.13.1 anyway and hope this helps to take it upstream.

**For reference**: the issue had a quite cumbersome flow - all tests are build with the same settings i.e., OpenMP runtime is linked even if OpenMP is not used. For the `malloc` test, the `OMP_PROC_BIND` (`tests/test.sh` or via `make test`) seems to trigger some OpenMP-runtime initialization, which pulls in a different implementation of realloc. The fault in my implementation was the assumption that realloc always returns the same pointer in case of success (however it can also allocate a new buffer at a different address and copy the original content).
