### ISSUE TITLE
[regression] .pc files contain references to build directories

### ISSUE THREAD

**Issue by yurivict** [hfp/libxsmm#347]
38ada493a installs, for example, lib/libxsmmnoblas.pc:
```
Name: libxsmm/noblas
Description: LIBXSMM substituted LAPACK/BLAS dependency
URL: https://github.com/hfp/libxsmm
Version: 1.13.0

prefix=/usr/ports/math/libxsmm/work/stage
includedir=${prefix}/include
libdir=${prefix}/lib

Requires: libxsmm
Cflags: -I${includedir}
Libs: -L${libdir} -lxsmmnoblas
```

prefix is wrong.

Also it is installed into a wrong path. It should be installed into ```$(PREFIX)/libdata/pkgconfig/```

**Comment by yurivict** [comment]
Original report was closed https://github.com/hfp/libxsmm/issues/334 but the problem still exists.

**Comment by hfp** [comment]
Did you built with the pkg-environment?  
I am asking this because LIBXSMM's `Makefile:1558` checks for `_PKG_CHECKED`.

I edited `/usr/ports/math/libxsmm/Makefile` to contain the following:

```make
DISTVERSION=    g20190826
GH_TAGNAME=     79f85d0
```
Building the library:

```bash
make clean
make makesum build
```

Then I get (`cat work/libxsmm-79f85d0/lib/libxsmmnoblas.pc`):

```text
Name: libxsmm/noblas
Description: LIBXSMM substituted LAPACK/BLAS dependency
URL: https://github.com/hfp/libxsmm
Version: 1.13.0

prefix=/usr/local
includedir=${prefix}/include
libdir=${prefix}/lib

Requires: libxsmm
Cflags: -I${includedir}
Libs: -L${libdir} -lxsmmnoblas
```

**Comment by yurivict** [comment]
Your installation logic is wrong.

You should install into $(STAGEDIR)$(PREFIX).
There is no need to define ```INSTALL_ROOT``` because the above variables exist.

**Comment by hfp** [comment]
Should be solved in [v1.14](https://github.com/hfp/libxsmm/releases/tag/1.14). Thank you for your patience!

**Comment by hfp** [comment]
@yurivict Is this issue fixed for you?  I am just asking since the BSD package remained at v1.10...

**Comment by yurivict** [comment]
@hfp Yes, this is still an issue.
