### ISSUE TITLE
libCEED Failures

### ISSUE THREAD

**Issue by jeremylt** [hfp/libxsmm#348]
libCEED is getting segfaults when compiled with LIBXSMM after https://github.com/hfp/libxsmm/commit/f7d72dca0593f307893ebe5ce5aea5f39dbb43d4

This is affecting all of our backends when the LIBXSMM backend is compiled into the library, even when LIBXSMM is not being used.

**Comment by hfp** [comment]
Thank your for your heads-up!  There is development going on, which made LIBXSMM/master instable over the course of the last 2-3 weeks. I hope this is resolved now, but I cannot generally guarantee to have a stable master for every commit and at any time. I believe master is stabilized now, and I would appreciate if you can (re-)try!

**Your input will be important to decide whether the developed feature will be available/enabled by default or if it needs a special build of LIBXSMM.** Generally, I recommend using our latest release for your regtesting (unless you rely on features only available in the master revision). I am sorry for the fluctuations caused on your end. Thank you again for alerting us and reporting this issue!

**Comment by jeremylt** [comment]
Thanks for the quick turnaround. I just didn't realize you guys did active development directly on master. It threw me for a loop because we've been pulling off master for our CI since January and everything has been fine.

Everything seems to work now.
