### ISSUE TITLE
Remove compiler generated fallback code

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#35]
Currently, LIBXSMM offers two fallback options: a) compiler generated and unrolled code b) call into a BLAS library. As it's planned to evolve LIBXSMM generator to support additional cases such as arbitrary alpha and beta and transpose options and LIBXSMM's JIT feature will become a stable release feature, alternative a) is redundant and will most likely never been called. Therefore it should be considered as deprecated and removed in a future release of LIBXSMM.

**Comment by hfp** [comment]
The C inlinable code path will be moved to libxsmm_fallback.h, and therefore removed from the main interface (libxsmm.h). Having the C code still available is to keep an eye on code quality the compiler is able to generate, and also to exercise our macro layer. The Fortran based inlinable/optimized code path will be removed also to avoid reworking the code (CONTIGOUS flag, etc.) to match the Fortran 2003 level.
