### ISSUE TITLE
Compilation error with -std=c99 if assert.h is included before libxsmm.h

### ISSUE THREAD

**Issue by jedbrown** [hfp/libxsmm#368]
This commit is responsible for the following compilation error. https://github.com/hfp/libxsmm/commit/310270acbddeba0bb7f9c8e733ab397ee306269e

```bash
$ cat a.c
#include <assert.h>
#include <libxsmm.h>
$ gcc -std=c99 -I$HOME/src/libxsmm/include -c a.c
In file included from /usr/include/sched.h:34,
                 from /usr/include/pthread.h:23,
                 from /home/jed/src/libxsmm/include/libxsmm_sync.h:469,
                 from /home/jed/src/libxsmm/include/libxsmm.h:51,
                 from a.c:2:
/usr/include/time.h:113:5: error: unknown type name ‘locale_t’
  113 |     locale_t __loc) __THROW;
      |     ^~~~~~~~
In file included from /home/jed/src/libxsmm/include/libxsmm_sync.h:469,
                 from /home/jed/src/libxsmm/include/libxsmm.h:51,
                 from a.c:2:
/usr/include/pthread.h:775:9: error: unknown type name ‘clockid_t’; did you mean ‘clock_t’?
  775 |         clockid_t __clockid,
      |         ^~~~~~~~~
      |         clock_t
```

I'm using gcc-9.2.0 with glibc-2.30. The same issue is present with clang-9.0.1.

**Comment by jedbrown** [comment]
For the record, I think this commit should be reverted. Futzing with `__USE_GNU` is not supported at all. It is defined automatically if one defines the feature test macro `_GNU_SOURCE`, but feature test macros *must* be defined before including headers, so there is no supported way for libraries to set them.
```
       NOTE: In order to be effective, a feature test macro must be defined be‐
       fore  including any header files.  This can be done either in the compi‐
       lation command (cc -DMACRO=value) or by defining the  macro  within  the
       source  code  before  including  any  headers.  The requirement that the
       macro must be defined before including any header  file  exists  because
       header  files may freely include one another.  Thus, for example, in the
       following lines, defining the _GNU_SOURCE macro may have no  effect  be‐
       cause  the  header <abc.h> itself includes <xyz.h> (POSIX explicitly al‐
       lows this):

           #include <abc.h>
           #define _GNU_SOURCE
           #include <xys.h>

       Some feature test macros are useful for creating portable  applications,
       by  preventing nonstandard definitions from being exposed.  Other macros
       can be used to expose nonstandard definitions that are  not  exposed  by
       default.
```

**Comment by hfp** [comment]
Thank you for reporting this issue!

> [...] with __USE_GNU is not supported [...]

Yes, `__USE_GNU` is an outcome of features.h eventually controlled by `_GNU_SOURCE`. Regarding whether this can/should be controlled, I agree as well. The above two dependencies are now more carefully crafted and the include order of header files wrt libxsmm.h is now tested. I am glad you brought this issue to attention!

**Comment by jedbrown** [comment]
Thanks. Your updates work for my environment, though there are still places where `_GNU_SOURCE` is defined in the header (which a user might not include first). This is unsupported and might upset a user wishing to compile with strict non-GNU features. Have you considered removing `libxsmm_sync.h` from `libxsmm.h`? It seems like the vast majority of users don't need this feature, and a user who does could include `libxsmm_sync.h` directly. I believe this would allow you to remove the `_GNU_SOURCE` definition from `libxsmm_macros.h`, thereby containing its side-effects in user code.

**Comment by hfp** [comment]
Yes, it's mostly used internally and could be contained in our `src` folder rather than `include`. I have to check if moving the header is (partially) possible (I need to check what's used in Eigen and Tensorflow).

I can remove _GNU_SOURCE, but need to test first. One change was to not rely on the outcome of what _GNU_SOURCE enables. I have to check what's leftover (even in `src` directory). Though, LIBXSMM can be used in header-only form, which effectively includes all of our source files.

**Comment by hfp** [comment]
I think we do not want to weed out our interface wrt "unused" functionality at this point. So far, we expose some functionality that is beyond LIBXSMM's main scope but it is widely used internally and potentially useful outside of our implementation realm. Our sample code might be seen as "external" as well. Though, the sync-layer is also [documented](https://libxsmm.readthedocs.io/libxsmm_aux/#thread-synchronization).

**Comment by jedbrown** [comment]
I'm only suggesting the modest API change that `libxsmm_sync.h` be included by users who need that functionality. In this case, I assume the issue is `pthread_yield`, which requires `_GNU_SOURCE`.

```
SYNOPSIS
       #define _GNU_SOURCE             /* See feature_test_macros(7) */
       #include <pthread.h>

       int pthread_yield(void);

       Compile and link with -pthread.
```
I think the safe and recommended thing is to instruct users to define `_GNU_SOURCE` if they will use this functionality.

**Comment by hfp** [comment]
I was misreading your comment, you suggested to only remove the sync header from the top-level header libxsmm.h. I will just check if this would break afore mentioned software (mostly TF) and the just do it.

All other things will get fallback code, e.g., pthread_yield. In fact, such code is already present but it must be selected depending on `__USE_GNU` etc.

**Comment by jedbrown** [comment]
Excellent, thanks!

**Comment by hfp** [comment]
Everything should be now in the master branch, i.e., separated sync layer and no "GNU control".
