### ISSUE TITLE
Broken memory wrapping implementation 

### ISSUE THREAD

**Issue by bertwesarg** [hfp/libxsmm#377]
Libxsmm obviously does not follow the documentation of wrapping symbols by using the linkers [`--wrap`](https://sourceware.org/binutils/docs-2.34/ld/Options.html#index-_002d_002dwrap_003dsymbol) option:

    

It clearly states, that the `__real_` functions should not be implemented in the same compilation unit then the `__wrap_` functions.

**Comment by hfp** [comment]
Hello Bert, thank you for your report! I will investigate this and resolve the issue. Out of curiosity, do you have a reproducer or an actual problem behind this report? I would be also interested if it was only a tool or some (static) analysis that brought this issue to your attention.

**Comment by bertwesarg** [comment]
It got my attention, while trying to solve a problem in combination with the [Score-P](https://score-p.org) performance measurement tool, which also wraps `malloc`. The main problem is, that Score-P uses compiler function instrumentation, and instrumenting the `__real_` functions looks not like a good idea. Though, moving this into a separate file wont solve this. But I just wanted to bring the current situation to your attention.

**Comment by hfp** [comment]
You may attribute the function(s) to get excluded from instrumentation. There is also an additional flag to black-list functions wrt instrumentation. Thanks again for the report!

**Comment by hfp** [comment]
Btw, you can turn off memory wrapper in LIBXSMM: `make MALLOC=0`.

**Comment by bertwesarg** [comment]
> You may attribute the function(s) to get excluded from instrumentation. There is also an additional flag to black-list functions wrt instrumentation. Thanks again for the report!

GCC is not the only compiler out there and the function instrumentation from GCC itself is one of the worst.
