### ISSUE TITLE
Get Segmentation Fault when using libxsmm_bmmdispatch

### ISSUE THREAD

**Issue by Yablon** [hfp/libxsmm#380]
I build the dynamic library using the following:
```
wget https://github.com/hfp/libxsmm/archive/1.14.tar.gz
tar xvf 1.14.tar.gz
cd libxsmm-1.14/
make STATIC=0
```

and the following code gives an segmentation fault error:
```
#include <libxsmm.h>
#include <vector>

int main(int argc, char* argv[]) {
  float alpha = 1.0;
  float beta = 1.0;
  typedef libxsmm_bfloat16 value_type;
  int batchsize = 1, m = 1, n = 32, k = 32;
  std::vector<value_type> a(batchsize*m*k), b(batchsize*k*n), c(m*n, 0);
  libxsmm_bmmfunction kernel;
  kernel = libxsmm_bmmdispatch(m, n, k, &m, &n, &k, &alpha, &beta, NULL, NULL);
  assert(kernel);
  for (int i = 0; i < batchsize; ++i) { /* initialize input */
    a[i*m*k] = static_cast<value_type>(1);
    b[i*k*n] = static_cast<value_type>(7);
  }
  /* kernel multiplies and accumulates matrix products: C += Ai * Bi */
  for (int i = 0; i < batchsize; ++i) kernel(&a[i*m*k], &b[i*k*n], &c[0]);
}
```

my bazel BUILD file is as following:
```
cc_library(
  name = "xsmm_avx",
  srcs = glob(["lib/*.so"]),
  hdrs = glob(
      [
          # trigger rebuild if template changed
          "src/template/*.c",
          "src/*.h",
          "include/*.h",
      ]
  ) + [
      # source files included internally
      "src/libxsmm_hash.c",
  ],
  includes = [
      "include",
      "src",
      "src/template",
  ],
  linkopts = ["-lpthread"],
  visibility = ["//visibility:public"],
)
```

Would you please tell me where I am wrong ?

**Comment by hfp** [comment]
Running a debug-build of this case (or using `LIBXSMM_VERBOSE=1` environment variable), unveils the following message:

```text
LIBXSMM ERROR (libxsmm_generator_gemm_kernel): unknown architecture or unsupported precision (error #90004)!
```

Granted, the error message could be improved. Anyhow, the prerequisite for running BFloat16 is "[CPX](https://github.com/hfp/libxsmm/blob/master/include/libxsmm_cpuid.h#L32)". We do not have fall-back code for BFloat16-based GEMM on earlier hardware (and CPX is not publicly available at this point in time).

**Comment by hfp** [comment]
( @alheinecke may want to comment on the [above note](https://github.com/hfp/libxsmm/issues/380#issuecomment-620059990) )

**Comment by alheinecke** [comment]
No the bug must be something else. There is fallback to AVX512. So the null pointer will only come on non-AVX512 platform, but AVX512 is fine.

Of course k%2 needs to hold true due to the instructions.

**Comment by Yablon** [comment]
@alheinecke I run a test on both an AVX512 supported machine and AVX256 supported machine, neither passes unfortunately.

**Comment by hfp** [comment]
For our own reference/documentation ("please ignore"), I dropped below content into LIBXSMM's root directory (file is called `BUILD`).

```text
cc_library(
    name = "xsmm_avx",
    srcs = glob(["lib/*.so"]),
    hdrs = glob(
        [
            # trigger rebuild if template changed
            "src/template/*.c",
            "src/*.h",
            "include/*.h",
        ]
    ) + [
        # source files included internally
        "src/libxsmm_hash.c",
    ],
    includes = [
        "include",
        "src",
        "src/template",
    ],
    linkopts = [
        "-lpthread",
        "-fopenmp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "simple",
    srcs = ["simple.cpp"],
    includes = [
      "include",
    ],
    deps = [
        "//:xsmm_avx"
    ],
)
```

The above given source code was called `simple.cpp` and dropped into the root folder as well. This depends on LIBXSMM built per `make STATIC=0` (DBG=1 may be advisable). Finally, I used [Bazelisk](https://github.com/bazelbuild/bazelisk) to build the example (`bazelisk build //:simple`).

**Comment by alheinecke** [comment]
It seems you use a very old version (1.14), please use the latest master. Again, we only support AVX512.

**Comment by Yablon** [comment]
Thank you @alheinecke . 
In my opinion, in matrix mulplication,
C = alpha * A * B + beta * b,
where A has a dimension (m, n), B has a dimension (n, k), and lda is m, ldb is n, ldc is k.

Am I right ?

And if I have a matrix with dimension 512 * 512, and a vector with dimension 512 * 1, is it possible that libxsmm show its power ? Or I will only get 1 / 512 of peak performance ?

Thank you !

**Comment by alheinecke** [comment]
No, LIBXSMM is following BLAS standard and is col-major that means in C:
A[K][M] , B[N][K] and C[N][M] -> C[N][M] = alpha *\sum_k A[k][M] * B[N][k] + beta*C[N][M]  \forall N,M
 
that means we have following requirements for LDs: LDA>=M, LDB>=K and LDC>=M

When you multiply a matrix with a vector, we are not bad, but this is not the focus. The focus is matrix X matrix. For (dense) matrix * vector even simply C code will do as this is a read memory bandwidth bound problem. 
Also we are focusing on sizes up to 128. Above one needs to assemble a custom operation using our fast micro kernels.

**Comment by Yablon** [comment]
@alheinecke Thank you for you reply. 
I am glad that I was wrong so I can go on a right way more quickly.

You said that multiply a matrix with a vector is not the focus, but actually I think we have needs for them. Have you heard [this repository](https://github.com/pytorch/FBGEMM) ? They have a "packed" concept and they will pack the matrix before computing and do the matrix vector muplication job for a lot of times which save the packing overhead and improve the inference speed.

My question is that, do you get different focus ? or more specificly, wil libxsmm act  as well as that repository ?

**Comment by alheinecke** [comment]
yes, we know FBGEMM. However, my concern/question is around matrix*vector. Even packing the matrix, you still have N^2 memory and N^2 compute operations and therefore you are still BW-bound.
Can you explain a bit more if you are looking into computer vision or natural language processing?

On how to use small matmul of LIBXSMM in deep learning I recommend the following reading:
https://arxiv.org/abs/1808.05567
https://arxiv.org/abs/1906.06440

**Comment by Yablon** [comment]
Thank you for your reply @alheinecke ,

I am looking into speech generation problems. Most of them are autoregresive models.

I will generate audios, with sample rate like 48k Hz. It means that when 1 second audio is generated, 24000 times of all matrix mulplications needs to be computed. 

Most of the matrix mulplications come from rnn cells, like grus and dense layers. Due to the limit of rnns, the mulplication has to be computed between a vector with size like (1, 512) and (512, 512).

Is it possible that FBGEMM performs as well as LIBXSMM ?

**Comment by alheinecke** [comment]
all of the libraries will be the same as they operation cannot ran run fast as it's memory bandwidth bound and not compute bound. I would suggest you look for a potentially batching approach in your application.

**Comment by Yablon** [comment]
@hfp The segmentation fault error is disappeared using the following code, but the result is not right.

```
#include <libxsmm.h>
#include <stdint.h>
#include <iostream>
#include <vector>


int main(int argc, char* argv[]) {
  float alpha = 1.0;
  float beta = 1.0;
  typedef libxsmm_bfloat16 value_type;
  int batchsize = 1, n = 32, m = 32, k = 32;

  std::vector<value_type> a(batchsize * m * k), b(batchsize * k * n);
  std::vector<float> c(m * n);
  for (int i = 0; i < 32 * 32; i++) {
    a[i] = 1;
    b[i] = 1;
    c[i] = 0;
  }
  libxsmm_bsmmfunction kernel;
  kernel = libxsmm_bsmmdispatch(m, n, k, &m, &k, &m, &alpha, &beta, NULL, NULL);

  for (int i = 0; i < batchsize; ++i) kernel(a.data(), b.data(), c.data());
  std::cout << "c" << std::endl;
  std::cout << c[0] << std::endl;

  std::cout << "a" << std::endl;
  std::cout << a[0] << std::endl;
  std::cout << "b" << std::endl;
  std::cout << b[0] << std::endl;
}
```

build file is 

```
cc_binary(
    name = "test_libxsmm",
    srcs = [
        "test_libxsmm.cc",
    ],
    copts = [
        "-fopenmp",
        "-D_OPENMP",
        "-m64",
        "-mfma",
        "-mavx512f",
        "-mavx512bw",
        "-mavx512dq",
        "-mavx512vl",
        "-masm=intel",
    ],
    linkopts = [
        "-fopenmp",
        "-lm",
    ],
    deps = [
        "@libxsmm_archive//:xsmm_avx",
    ],
)
```

the output is 

```
LIBXSMM WARNING: highly optimized non-JIT code paths are limited to "hsw"!

LIBXSMM WARNING: timer is maybe not cycle-accurate!
c
0
a
1
b
1

LIBXSMM_VERSION: master-sc20_paper-95 (1593835520)
CLX/SP      TRY    JIT    STA    COL
   0..13      0      0      0      0
  14..23      0      0      0      0
  24..64      1      1      0      0
Registry and code: 10 MB + 20 KB
```

where c[0] should be 32.

Can you point out where I am wrong ? Thank you !

**Comment by hfp** [comment]
I believe “1” is not 1.0 in terms of Bfloat16. You need a conversion or use a ready to use copy-in routine. That’s because C/C++ does not yet support any FP type smaller than SP. You may find quantization code in our bf16 sample code or find some ready to use routine perhaps in libxsmm_dnn.h.

**Comment by hfp** [comment]
For C++ we can perhaps improve with a type that does the conversion by implementing a suitable c’tor/d’tor.

**Comment by Yablon** [comment]
Thank you !

**Comment by alheinecke** [comment]
yes you need to use this function: https://github.com/hfp/libxsmm/blob/master/src/libxsmm_dnn.c#L714 
or the union directly in your code without RNE rounding, but truncation: 
    libxsmm_bfloat16_hp t;
    t.f = (float)1;
    mybf16data[i] = t.i[1];
