### ISSUE TITLE
Load selector operands for permutes from memory for csr_asparse_reg

### ISSUE THREAD

**Issue by mahudu97** [hfp/libxsmm#385]
As we know, we can load the selector operands from memory instead of storing them in register to increase the number of unique NNZs from 176 / 224 for DP/SP, to 240 / 480. 

This can be used after running into the previous limit.

**Comment by mahudu97** [comment]
Some testing has shown that using N blocking great than 1 can provide speedups of around 1.1x to 1.3x for some sparse PyFR matrices.

As code is present for N blocking, (just set to 1), I thought it would be good to at least have a note it could be used again, if registers are free.

**Comment by alheinecke** [comment]
thanks! Yeah, this is a good trick.

Can you also commit some testers for SP? That would be very helpful.

**Comment by mahudu97** [comment]
Glad to know you like the N blocking as well.

I have the test cases currently as text files but they can be generated during the test easily. However, I'm not too sure on how the testing/CI is setup for this repo.

If you meant something like `libxsmm/tests`, then a `spgemm_csr_asparse` in the same fashion as https://github.com/hfp/libxsmm/blob/master/tests/gemm.c could work.

Otherwise, something like https://github.com/hfp/libxsmm/blob/master/samples/smm/specialized.cpp but only for the case of streaming B and C, store A in cache? 

In either case, it's probably just as easy to adapt anything new to test both DP and SP, if preferred?

**Comment by alheinecke** [comment]
closing this issue as the code was merged.
