### ISSUE TITLE
remove ALIGNED_STORES and ALIGNED_LOADS options

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#39]
currently the LIBXSMM has two build options which control implicit changes of LDA and LDC parameters. 
As we are moving to a more general interface which includes support for LDx ALIGNED_STORES and ALIGNED_LOADS are redundant and should be removed.
LIBXSMM should still provide macros or functions which allow for easily deriving "padded" LDx values matching the smallest required value.

**Comment by hfp** [comment]
This issue makes only sense together with the statement in issue #40: "do not suffer from performance penalties [...]". The options ALIGNED_LOADS and ALIGNED_STORES are **not** only rounding up  the leading dimensions (LDA, LDC), but also ultimately *permitting* the generation of aligned LD/ST. Though, knowing that LDx is a multiple of the vector-width is not enough to safely rely on aligned LD/ST. So, removing this support really boils down to whether or not we want to support KNC.

**Comment by hfp** [comment]
The meaning of the flags will be re-purposed in order to make this truly/more useful as well as safer and less magic.
