### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by antoscha** [hfp/libxsmm#390]
I'm not sure if it's related to the project, but I'm getting the following error at `make tests`:

```
In file included from matcopy.c:33:
/usr/include/f77blas.h:476:5: error: unknown type name ‘bfloat16’; did you mean ‘_Float16’?
  476 |     bfloat16 *, blasint *, bfloat16 *, blasint *, float *, float *, blasint *);
      |     ^~~~~~~~
      |     _Float16
/usr/include/f77blas.h:476:28: error: unknown type name ‘bfloat16’; did you mean ‘_Float16’?
  476 |     bfloat16 *, blasint *, bfloat16 *, blasint *, float *, float *, blasint *);
      |                            ^~~~~~~~
      |                            _Float16
make[1]: *** [Makefile:138: obj/matcopy-c.o] Error 1
```

**Comment by hfp** [comment]
I have investigate this and it looks like "bfloat16" is not defined in any of the headers of OpenBLAS. It is defined in the source tree, but not in the interface.

```bash
[openblas/include]$ grep bfloat *
f77blas.h:         bfloat16 *, blasint *, bfloat16 *, blasint *, float *, float *, blasint *);
```

So none of the files in that directory define that type and non of the includes contain such definition. The interface is either incomplete or assuming a compiler with a built-in type called "bfloat16".

**Comment by hfp** [comment]
The issue with OpenBLAS should be avoided in v1.16.1; feel free to reopen/create another issue if you encounter a problem. Thank you very much for your contribution and report!
