### ISSUE TITLE
The result of BF16 gemm is not correct

### ISSUE THREAD

**Issue by heagoo** [hfp/libxsmm#395]
I am trying to use the BF16 gemm, and found the result is not correct, here is the testing code:
(I see the comment in header file is to call bsgemm for BF16 input, thus I suppose here the testing code is correct)

#include <libxsmm.h>
#include <cstdlib>

template<typename T>
void init_buf(T *buf, int size) {
  for (int i = 0; i < size; ++i) {
    buf[i] = (T)(1.0f * rand() / RAND_MAX);
  }
}

int main() {
  float alpha = 1;
  float beta = 0;
  int dim = 32;
  float *A = new float[dim * dim];
  float *B = new float[dim * dim];
  float *C = new float[dim * dim];

  init_buf(A, dim * dim);
  init_buf(B, dim * dim);

  libxsmm_mmfunction<float> kernel(LIBXSMM_GEMM_FLAG_NONE, dim, dim, dim, alpha, beta);
  assert(kernel);
  kernel(A, B, C);
  printf("C[0]=%f, C[1]=%f\n", C[0], C[1]);

  libxsmm_bfloat16 *bfA = new libxsmm_bfloat16[dim * dim];
  libxsmm_bfloat16 *bfB = new libxsmm_bfloat16[dim * dim];
  libxsmm_rne_convert_fp32_bf16(A, bfA, dim * dim);
  libxsmm_rne_convert_fp32_bf16(B, bfB, dim * dim);

  libxsmm_bsgemm(NULL, NULL, &dim, &dim, &dim, &alpha, bfA, &dim, bfB, &dim, &beta, C, &dim);
  printf("C[0]=%f, C[1]=%f\n", C[0], C[1]);

  return 0;
}

Compile command:
g++ test_bf16.cpp -I./include -lxsmm -L./lib -lblas -o test

**Comment by hfp** [comment]
It is likely caused by an incorrect/absent overload of `libxsmm_mmfunction` wrt Bfloat16. I will add the necessary support for Bfloat16 to our C++ layer.

**Comment by alheinecke** [comment]
A needs to be formatted inVNNI layout ([K][M] --> [K/2][M][2], so two entries of "K" need to become the inner-most dimension) and the VNNI_A flag needs to be set 1 when creating the routine. It's the caller responsibility to provide an A in VNNI layout as it makes performance-wise no sense to have VNNI reformats in the small GEMMs. Think of the VNNI Flag as a Transpose Flag of GEMMs.

under samples/xgemm/kernel.c the VNNI layout is showcased.

Bonus: if you want to use int8, the VNNI format is [K][M] -> [K/4][M][4] and similar flags need to be set.

**Comment by heagoo** [comment]
Got you. I think document is needed to make everyone notice that. Thanks!
