### ISSUE TITLE
LIBXSMM_GEMM_FLAG_VNNI

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#397]
When requesting and generating a Bf16 SMM-kernel, it is apparently required to fuse LIBXSMM_GEMM_FLAG_VNNI_A into the set of flags. Is this to support (future) on-the-fly conversion?

Anyhow, we may want to invert the logic and introduce LIBXSMM_GEMM_FLAG_**NO**_VNNI_A (or similar) to ease using our generator functions and interface. This would allow to omit LIBXSMM_GEMM_FLAG_VNNI_A and assume it is in the necessary format.

**Comment by alheinecke** [comment]
No the logic is as want to generator need special formats and calling software needs to reformat the data, Also we might want add slow code in future which does the conversion on the fly for easy layouts on the software. So this flags reminds everyone that something is special. 

We also don't have NO_TRANS flags, conceptually VNNI is like Transpose.
