### ISSUE TITLE
link Error (build requirements?)

### ISSUE THREAD

**Issue by maxhutch** [hfp/libxsmm#4]
I'm trying to run libxsmm on a CPU-only ([IvyBridge-E](http://ark.intel.com/products/77780/Intel-Core-i7-4930K-Processor-12M-Cache-up-to-3_90-GHz)) system with a somewhat dated compiler:
```
maxhutch@edoras:~/src/clean-tests/RTI-LST$ ifort --version
ifort (IFORT) 14.0.1 20131008
Copyright (C) 1985-2013 Intel Corporation.  All rights reserved.
```

At link, it gives some warnings about some MIC things and then dies with an opaque `Error 100`, maybe related to missing `x86_64-k1om-linux-ld`:
```
/opt/openmpi-intel/bin/mpif90 -g -check all -debug all -traceback  -o nek5000 -ffpe-trap=invalid,zero,overflow -fsignaling-nans -I/opt/fftw3/include/ -I/home/maxhutch/src/libxsmm/include obj/test.o obj/kinds_mod.o obj/mpif.o obj/fftw3.o obj/size_mod.o obj/speclib.o obj/mesh_mod.o obj/input_mod.o obj/parallel_mod.o obj/fft_fftw_mod.o obj/ctimer_mod.o obj/dealias_mod.o obj/domain_mod.o obj/dxyz_mod.o obj/eigen_mod.o obj/esolv_mod.o obj/fdmh1_mod.o obj/geom_mod.o obj/hsmg_mod.o obj/interp_mod.o obj/ixyz_mod.o obj/mvgeom_mod.o obj/nekuse_mod.o obj/opctr_mod.o obj/restart_mod.o obj/scratch_mod.o obj/semhat_mod.o obj/soln_mod.o obj/steady_mod.o obj/string_mod.o obj/topol_mod.o obj/tstep_mod.o obj/turbo_mod.o obj/wz_mod.o obj/wzf_mod.o obj/zper_mod.o obj/io_mod.o obj/poisson_mod.o obj/navier4.o obj/drive.o obj/drive1.o obj/drive2.o obj/plan4.o obj/bdry.o obj/coef.o obj/conduct.o obj/connect1.o obj/connect2.o obj/dssum.o obj/eigsolv.o obj/genxyz.o obj/hsmg.o obj/gmres.o obj/convect.o obj/induct.o obj/navier0.o obj/navier1.o obj/navier5.o obj/navier6.o obj/navier8.o obj/map2.o obj/ic.o obj/ssolv.o obj/math.o obj/mxm_wrapper.o obj/hmholtz.o obj/subs1.o obj/fast3d.o obj/fasts.o obj/byte.o obj/chelpers.o obj/byte_mpi.o obj/prepost.o obj/nek_comm.o obj/setprop.o obj/papi.o obj/gauss.o obj/makeq.o obj/makeq_aux.o obj/mxm_std.o obj/comm_mpi.o obj/singlmesh.o obj/jl_gs.o obj/jl_sort.o obj/jl_sarray_transfer.o obj/jl_sarray_sort.o obj/jl_gs_local.o obj/jl_crystal.o obj/jl_comm.o obj/jl_tensor.o obj/jl_fail.o obj/jl_fcrystal.o obj/jl_findpts.o obj/jl_findpts_local.o obj/jl_obbox.o obj/jl_poly.o obj/jl_lob_bnd.o obj/jl_findpts_el_3.o obj/jl_findpts_el_2.o obj/jl_sparse_cholesky.o obj/jl_xxt.o obj/jl_fcrs.o -lblas -llapack -L/opt/fftw3/lib/ -lfftw3 -L/home/maxhutch/src/libxsmm/lib/intel64 -lxsmm
ifort: command line warning #10006: ignoring unknown option '-ffpe-trap=invalid,zero,overflow'
ifort: command line warning #10006: ignoring unknown option '-fsignaling-nans'
ifort: warning #10182: disabling optimization; runtime debug checks enabled
ifort: command line warning #10006: ignoring unknown option '-ffpe-trap=invalid,zero,overflow'
ifort: command line warning #10006: ignoring unknown option '-fsignaling-nans'
ifort: warning #10362: Environment configuration problem encountered.  Please check for proper MPSS installation and environment setup.
ifort: warning #10182: disabling optimization; runtime debug checks enabled
x86_64-k1om-linux-ld: No such file or directory
makefile:165: recipe for target 'nek5000' failed
make: *** [nek5000] Error 100
```

**Comment by alheinecke** [comment]
Hard time finding an ICC 14 machine here... I simply don't know if icc 14 already supports the -no-offload flag. Can you try to build libxsmm with OFFLOAD=0 (which should be the default) ? 

Can you share your libxsmm build command?

**Comment by maxhutch** [comment]
I thought I had been building with `OFFLOAD=0`:
```
make $* M="4 8 10 12 16 64 100 144" N="4 8 10 12 16 64 100 144" K="4 8 10 12" \
    BETA=0 OFFLOAD=0 MIC=0 SSE=3
```

**Comment by alheinecke** [comment]
After having looking into this, this is possible a problem in our frontend (relying on default compiler flags). Can you please add -no-offload when building the F90 mod and your whole application?

in libxsmm_macros.h we read this flag... (#ifdef __INTEL_OFFLOAD)

**Comment by maxhutch** [comment]
When I append that to the make line:
```
make $* M="4 8 10 12 16 64 100 144" N="4 8 10 12 16 64 100 144" K="4 8 10 12" \
    BETA=0 OFFLOAD=0 MIC=0 SSE=3 -no-offload
```
no module is generated:
```
maxhutch@edoras:~/src/libxsmm$ ls include/
libxsmm_fallback.h  libxsmm_macros.h  libxsmm.modmic  libxsmm_prefetch.h
```

**Comment by alheinecke** [comment]
I meant in all other steps than this make call. For me this compiles and builds a static lib with -no-offload.

I believe the problem appears when you compile the f90 file to a module. This compilation has to happen as well as with -no-offload.

**Comment by alheinecke** [comment]
make M="4 8 10 12 16 64 100 144" N="4 8 10 12 16 64 100 144" K="4 8 10 12" BETA=0 OFFLOAD=0 MIC=0 SSE=3

generates:
[aheineck@aheineck-linux libxsmm_github]$ ls include/
libxsmm.f90  libxsmm_fallback.h  libxsmm.h  libxsmm_macros.h  libxsmm_prefetch.

When no compiling the f90 to a module with ifort, -no-offload is needed

**Comment by maxhutch** [comment]
Yes, adding `-no-offload` to the compilation of `libxsmm.f90` worked.

**Comment by alheinecke** [comment]
Glad to hear this. Since this problem also also shows up in C/C++ apps, I have created a new issue and close this one.

**Comment by alheinecke** [comment]
can you please try the latest commit?

It shouldn't required you to add -no-offload to your compiler command line to compile the f90 interface. Please note, we now remove offload support -> you need to re-compile libxsmm to enabled offloading to KNC

**Comment by maxhutch** [comment]
Yes, that works for me now.  Thanks!
