### ISSUE TITLE
remove generation for aligned stores and loads from the generator backend

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#40]
All recent IAs (Sandy Bridge or later) do not suffer from performance penalties when executing a unaligned vector load (vmovups/vmovupd) on aligned data (so in theory we could use vmovaps/vmovapd). Therefore, we can take this complexity out of the generator backend. 

Side-note: this would also mean that the Intel Knights Corner backend needs to be removed, or at least limited to aligned LDx. This is due to the fact that the previous statement is not true on Intel Knight Corner as this architecture does not offer simple unaligned vector data move instructions.

**Comment by hfp** [comment]
Let's reject this since issue #39 is now fixed such that this ability becomes more useful again (perhaps also outside of KNC).
