### ISSUE TITLE
About INT8 GEMM

### ISSUE THREAD

**Issue by Gxllii** [hfp/libxsmm#408]
Hi, I found that the int8 data type is supported by libxsmm. Is there any documentation or sample on how to use it? Thanks in advance!

**Comment by alheinecke** [comment]
samples/xgemm

./kernel 68 44 56 68 56 68 1 0 0 0 0 0 nopf SUI8UI8 nobr 1 0 1

**Comment by Gxllii** [comment]
> samples/xgemm
> 
> ./kernel 68 44 56 68 56 68 1 0 0 0 0 0 nopf SUI8UI8 nobr 1 0 1

Thanks.

**Comment by Gxllii** [comment]
Hi @alheinecke ,
I would like to perform int8 gemm  (int8 input and int32 output) with avx-512 vnni instructions. I have built libxsmm and samples/xgemm with `make AVX=3` and then execute the sample with `./kernel 68 44 56 68 56 68 1 0 0 0 0 0 nopf SUI8I32 nobr 1 0 1`. The output shows it achieves about 140 gflops, which is much less than the peak performance of the evaluated machine. I guess that I didn't really use the vnni instructions. Could you please give me some guidance for this?

**Comment by hfp** [comment]
( putting `AVX=3` may only improve the performance of the naive code path that is part of the example.  
  LIBXSMM in this case does require to be built with non-default flags )

I think your 140 GFLOPS are single-core performance. The `kernel` sample code is not OpenMP (or otherwise) parallelized. Further, the short execution time of the kernel may be affected by Turbo frequency or better said the ability to guarantee certain Turbo freq. in case of single-threaded execution.

**Comment by alheinecke** [comment]
The code generates AVX512-VNNI, however you need a Cascalake or newer CPU. Also the shapes are "ugly" so there is masking etc. going on. And then you need a higher iteration count, fixing both, e.g.:
./kernel 64 64 64 64 64 64 1 0 0 0 0 0 nopf SUI8I32 nobr 1 0 10000

**Comment by Gxllii** [comment]
Get it. I have changed the iterations count and the result looks reasonable now. Thanks y’all.

**Comment by hfp** [comment]
Thank you for talking back! Feel free to reopen or report an new issue any time.

**Comment by Gxllii** [comment]
Hi,
How should I store the matrices when using int8 gemm (C=AB+C)?
What's the data layout for the A, B, and C should be?

**Comment by alheinecke** [comment]
The A matrix has to be VNNI format and the B matrix in normal format. That means the K-dimension needs to be divisible by 4:
C[N][M] = A[K/4][M][4] * B[N][K] + C[N][M]
This is also shown in the corresponding examples in samples/xgemm/kernel.c
