### ISSUE TITLE
clBLAS-master\src\library\blas\xgemm.cc(394): error C2065: 'gemmSelectKernel': nichtdeklarierter Bezeichner (not declared)

### ISSUE THREAD

**Issue by ReneBraun** [hfp/libxsmm#41]
Hi there, 
I struggle to create a cblas.lib using Visual Studio (desktop) 2012 since days and I just can't get it to compile correctly.
The long list of errors starts with 

clBLAS-master\src\library\blas\xgemm.cc(394): error C2065: 'gemmSelectKernel': nichtdeklarierter Bezeichner

after that there's a lot of errors aorund <precision> which I presume are just follow ups. Can anyone help?

Many thanks, 
René

**Comment by alheinecke** [comment]
I don't see how this is related to LIBXSMM, I guess you want to open an issue here: https://github.com/clMathLibraries/clBLAS?!
