### ISSUE TITLE
transposition

### ISSUE THREAD

**Issue by wangyi-fudan** [hfp/libxsmm#410]
Dear devoloper of libxsmm:
  I notice that TransA is not allowed. 
  I need to program a tiny deep neural network. It seems to me that in backpropagation, TransA is necessary.
  Is my math wrong or TransA is really needed?

**Comment by egeor** [comment]
You are right, it is needed in backpropagation, and currently we do not support transA.
However, in our DL primitives we merely transpose upfront A and then perform a non-transposed operation. E.g. look here for bwd_d in CNNs:

https://github.com/hfp/libxsmm/blob/master/src/template/libxsmm_dnn_convolve_st_bwd_custom_custom_generic.tpl.c#L51
