### ISSUE TITLE
Explanation of libxsmm internal tensor format?

### ISSUE THREAD

**Issue by tjingrant** [hfp/libxsmm#434]
Hello! I'm interested to learn more about the details of libxsmm internal buffer format. I find it useful for my understanding to look at copyin/copyout kernel implementation (and please let me know if there're better materials to read to understand them!). However, the semantics of specific variables crucial to understand the internal buffer format remain obscure to me, and I hope you can shed some light on them to help with my understanding:

For instance, in the following code snippet:
https://github.com/hfp/libxsmm/blob/ef82db6af66720d349a91dec65a0e6a070a16153/src/template/libxsmm_dnn_tensor_buffer_copy_in_nchw.tpl.c#L13

What does `lpb`, `bfm`, `fmb` mean? They seem to be additional tensor dimensions created from partitioning the input channel dimension. 

Similarly, could you help explain what these variables mean in the following snippet:
https://github.com/hfp/libxsmm/blob/ef82db6af66720d349a91dec65a0e6a070a16153/src/template/libxsmm_dnn_tensor_filter_copy_in_kcrs.tpl.c#L14

Specifically, how do I decode variable names (and their meanings) like `lpb`, `bofm`, `bifm`, `ifmb`, `ofmb`?

Many thanks in advance for your help!

**Comment by alheinecke** [comment]
sorry this one slipped through and I saw it today while cleaning up.

lpb = blocking for low precision VNNI format. That means for BF16 it's 2 and for int8 it's 4, this is also applied to channels.
bfm/fmb = blocking of feature maps, that is to split the C/K (feature map , fm) dimension into 2 parts for better cache associativity.

bofm,bifm,ifmb,ofmb: "i" input channels ("C"), "o" output channels ("K")

We can recommend for further reading:
https://arxiv.org/abs/1808.05567
https://arxiv.org/abs/1906.06440
