### ISSUE TITLE
Change unsigned to signed int for the loops to work correctly...

### ISSUE THREAD

**Issue by ddkalamk** [hfp/libxsmm#448]
`i` and `M` should be signed int below otherwise `M - 15` is a very large number when M is less than 15. Same applies in many other places...

https://github.com/hfp/libxsmm/blob/f8994bee45316343a3ef39ed796e7ad4920347ed/samples/eltwise/eltwise_dropout.c#L72-L77

**Comment by alheinecke** [comment]
M and i are per definition unsigned datatypes (they cannot be negative), I guess the condition needs a fix, something like, (M/16)*16 or so.

**Comment by ddkalamk** [comment]
Either is fine. May be use `i < (M & ~0xF)`. I feel `M - 15` was more readable...

**Comment by alheinecke** [comment]
OK, feel free to change to what solution is most readable, while keeping the unsigned values as the dimensions cannot be negative.

**Comment by alheinecke** [comment]
you can look at several macros: https://github.com/hfp/libxsmm/blob/master/include/libxsmm_macros.h#L465

**Comment by alheinecke** [comment]
push was done to fix this.
