### ISSUE TITLE
random test failures on MacOS conda-forge build

### ISSUE THREAD

**Issue by ltalirz** [hfp/libxsmm#454]
Hi, in the libxsmm conda-forge feedstock, we're seeing random failures of the `timer` test for the MacOS platform (linux works fine).
```
Running tests
=============
1 of 17 (atomics)... OK 
2 of 17 (gemm)... OK 
3 of 17 (gemmflags)... OK 
4 of 17 (hash)... OK 
5 of 17 (headeronly)... OK 
6 of 17 (malloc)... OK 
7 of 17 (matcopy)... OK 
8 of 17 (matdiff)... OK 
9 of 17 (math)... OK 
10 of 17 (memory)... OK 
11 of 17 (mhd)... OK 
12 of 17 (registry)... OK 
13 of 17 (rng)... OK 
14 of 17 (threadsafety)... OK 
15 of 17 (timer)... FAILED(13) 
make: *** [Makefile:1272: tests] Error 2
```

See discussion in https://github.com/conda-forge/libxsmm-feedstock/pull/13#issuecomment-761519952
Do you happen to have any ideas what might be causing this?

One thing I noticed is that even when the tests on MacOS occasionally pass, the output is different from the one on Linux:

MacOS
```
15 of 17 (timer)... OK 
```

Linux
```
15 of 17 (timer)... OK seconds=16.000652 delta=0% interrupted=0 tsc=false
```
Not sure whether this helps.

Here's the build script we are using: 
https://github.com/conda-forge/libxsmm-feedstock/blob/master/recipe/build.sh

**Comment by hfp** [comment]
Is this a virtualized macOS environment, i.e., running on top of a guest OS?

**Comment by ltalirz** [comment]
Thanks for the follow-up @hfp 

I notice that I forgot to include the link to the CI logs; here it is: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=263603&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1384

These are Azure runners with the [Macos virtual environment](https://github.com/actions/virtual-environments/blob/macOS-10.15/20201212.1/images/macos/macos-10.15-Readme.md)

I read [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware) that the macOS images are running in virtual machines provisioned on Mac Pros - I don't know more about the details of this virtualization. Does this already help?

This is on

**Comment by hfp** [comment]
@ltalirz Thank you for using LIBXSMM and opening an issue!

You may set an environment variable `TIMER_DELTA=-1`, which will avoid the test failure. This should not be worrisome since the timer test is calibrated to meet certain (but arbitrary) accuracy. Virtualized environments can generally cause (arbitrary) inaccuracy and may be unable to meet (any) tolerance. A failing timer test is just a sign that you should avoid collecting benchmark results that claim to be accurate measurements.

**Comment by ltalirz** [comment]
Thanks for the explanation!

@jan-janssen Can you try this?

**Comment by jan-janssen** [comment]
@hfp thanks a lot. 

@ltalirz yes, adding the flag fixed the tests. 

The differences in the timings are:
```
15 of 17 (timer)... OK seconds=16.417713 delta=-15% interrupted=0 tsc=false
```
vs.
```
15 of 17 (timer)... OK seconds=16.509662 delta=+14% interrupted=0 tsc=false
```
I now released a new conda package for `libxsmm` and restarted the pull request for the `cp2k` conda package. 

@hfp If you are interested in joining me in maintaining the conda package for `libxsmm` I would be happy to add you to the list of maintainers.

**Comment by hfp** [comment]
@jan-janssen Thank you for helping with this issue!  Yes, please add me to the list.  I may also use this to have a look at the CP2K package, etc.

**Comment by jan-janssen** [comment]
@hfp I added you to the conda package of `libxsmm` you should receive an invitation via email to join the GitHub group. Alternatively you can go to https://github.com/orgs/conda-forge/invitation to accept the invitation.
