### ISSUE TITLE
Accuracy result for sparse training examples?

### ISSUE THREAD

**Issue by jgong5** [hfp/libxsmm#456]
The sparse training examples (https://github.com/hfp/libxsmm/commits/master/samples/deeplearning) are very interesting. May I know if you have accuracy result for the models in the examples? Thanks.

**Comment by alheinecke** [comment]
We trained ResNet50 and DLRM with TB dataset with this code and matched accuracy. We also reproduced Google's work that Transformer has some problems. 
Some more details:
https://github.com/hfp/libxsmm/files/4671016/2020_05_22_LIBXSMM_Sparse_JIT_public.pdf

**Comment by jgong5** [comment]
> We trained ResNet50 and DLRM with TB dataset with this code and matched accuracy. We also reproduced Google's work that Transformer has some problems.

Thanks. Do you have more detailed results on the accuracy side, e.g. the accuracy from ResNet-50 and DLRM, and the issues from Transformer? The slides look great though it only covers the performance part.

**Comment by alheinecke** [comment]
RN50 is withing 0.5% with 75% sparsity and DLRM is withing 0.005% for ~90% sparsity in the MLPs. Transformer was off by more than 3 BLEU points as Google also reported. We are working on a detailed report using our operators.

**Comment by alheinecke** [comment]
closing the issue for now.
