### ISSUE TITLE
ARM/SMM: code-generation error for kernel request with empty shape

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#462]
Code-generation targeting ARM does not adhere to non-NULL kernel policy, i.e., it errors out if a kernel is requested with an empty shape like M, N, or K being zero (GEMM). Once resolved, [tests/gemm](https://github.com/hfp/libxsmm/blob/master/tests/gemm.c#L68) should be (re-)adjusted.

**Comment by lingweiyang** [comment]
Is the installation process of libxsmm on arm the same as that of X86? What do I need to pay attention to?

**Comment by alheinecke** [comment]
It's the same... However I don't get why such a question is asked in an unrelated & closed issue...
