### ISSUE TITLE
LIBXSMM_GEMM_DESCRIPTOR macro is broken for sparse

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#47]
the LIBXSMM_GEMM_DESCRIPTOR in libxsmm_generator.h doesn't allow for values 0 for LDA,LDB and LDC. However, these exception cases are used by the sparse matrix code generator for determining which matrix is sparse. A workaround was added generator_driver.c (simply overwriting the generated descriptor).

However, automatically promoting LDA - LDC to m or k seems to be a pretty dangerous thing. If the users requests such a code -> no DGEMM as this is an invalid specification. An error should be issued during generation of such a code instead.

**Comment by hfp** [comment]
ACK, however I would not call it "broken" since hooking up LDA/LDB as a sparse-flag it is entirely undocumented (which is in contrast to libxsmm_gemm_flags and libxsmm_gemm_xflags).
