### ISSUE TITLE
Automatic Affinity Considered Harmful

### ISSUE THREAD

**Issue by FreddieWitherden** [hfp/libxsmm#475]
Over the past few days I've been trying to debug why some of my tests run slower with libxsmm loaded and initialized than without.  After some digging I found it was because of:

https://github.com/hfp/libxsmm/blob/master/src/libxsmm_main.c#L948

which automatically sets process affinity if none is specified.  This was causing problems on two counts.  Firstly, on my quad-core machine GOMP fails to correctly identify which cores are logical and which are physical.  As such OMP_PROC_BIND with OMP_NUM_THREADS=4 pins four threads across *two* physical cores.   Performance hence suffers greatly compared with not pinning.  Secondly, as our application is hybrid MPI + OpenMP it is normal to test with 4 MPI ranks and OMP_NUM_THREADS=1.  Here, if OMP_PROC_BIND is specified with the out of the box defaults for mpich (which does not pin ranks) each process will pin itself to the first core.  Performance is again substantially worse than without pinning.

Given this, it would be nice if libxsmm did not pin by default on the principle of 'no surprises'.

**Comment by hfp** [comment]
Hmm, `OMP_PROC_BIND=TRUE` is used which is like `OMP_PROC_BIND=SPREAD`, i.e., on a quad-core with SMT/HT enabled `OMP_NUM_THREADS=4` should put one thread per physical core. Further, if MPI is linked into the application, the auto-pinning should be off by default (code attempts to discover MPI).

Anyhow, what I can do is turning auto-pin totally off by default (and may explicitly turn it on for our sample codes). **Would this solve the problem?**

---
P.S.: I recently had an unrelated problem with Debian, which quietly appended `nosmt` to the Linux kernel's boot line over the course of some updates in the past (which put some of the cores offline).

**Comment by FreddieWitherden** [comment]
So for us MPI is dynamically loaded at runtime *after* we have loaded and initialised libxsmm.  I guess this is why the auto-pinning code does not pick it up.  Disabling it by default, or providing an environmental variable to allow us to disable it, would be ideal.

As for why GOMP is getting confused I am not entirely sure; it should have no trouble discovering the topology:
```
lscpu --all --extended
CPU SOCKET CORE L1d:L1i:L2:L3 ONLINE    MAXMHZ   MINMHZ
0      0    0 0:0:0:0          yes 3500.0000 800.0000
1      0    1 1:1:1:0          yes 3500.0000 800.0000
2      0    2 2:2:2:0          yes 3500.0000 800.0000
3      0    3 3:3:3:0          yes 3500.0000 800.0000
4      0    0 0:0:0:0          yes 3500.0000 800.0000
5      0    1 1:1:1:0          yes 3500.0000 800.0000
6      0    2 2:2:2:0          yes 3500.0000 800.0000
7      0    3 3:3:3:0          yes 3500.0000 800.0000```

**Comment by hfp** [comment]
This is resolved (disabled auto-pin by default). Thank you for reporting the problem!
