### ISSUE TITLE
add support for vendor-specific (e.g. CRAY) wrappers to at least LIBXSMM samples

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#48]
running on Cray machines is easiest when using the cray wrappers for gnu/intel compilers. They are CC=cc CXX=CC FC=ftn. Currently makefiles can be hacked (incl. STATIC=1) to build on cray.

Often on cray machines, the login node has a different arch then the compute node, but the wrappers have the best arch flags -> LIBXSMM's cray support shouldn't specify -xHost.

**Comment by hfp** [comment]
See commit cd5cbc3.

**Comment by hfp** [comment]
This is fixed in the CRAY environment that I had at hand. In general, the compiler detection is changed to be name-based (identified using --version flag) rather than based on the executable name (wrapper).
