### ISSUE TITLE
KNC code generation

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#5]
KNC is generated although not requested:

make M="4 8 10 12 16 64 100 144" N="4 8 10 12 16 64 100 144" K="4 8 10 12" BETA=0 OFFLOAD=0 MIC=0 SSE=3

Furthermore, when calling with OFFLOAD=0, the application shouldn't be required to use -no-offload.

This is true for compiling the f90 module or including the libxsmm.h header in C/C++ applications.

**Comment by alheinecke** [comment]
fixed

**Comment by maxhutch** [comment]
Works for me too!
