### ISSUE TITLE
LIBXSMM_CODE_MAXSIZE is too small for some PyFR kernels

### ISSUE THREAD

**Issue by FreddieWitherden** [hfp/libxsmm#502]
While investigating the performance of the p6 PyFR hexahedral kernels (https://github.com/hfp/libxsmm/tree/master/samples/pyfr) it was found that some of the sparse register kernels fail to JIT due to hitting the max code size limit (128 KiB).  This causes them to fall back to dense kernels.  Doubling the max code size resolves this issue and results in substantially better performance.

Ideally, we would work to reduce the size of the generated kernels (and I have some ideas here).  But as an interim solution it would be nice if the size could be increased (or made flexible enough so that the sparse generation kernels can request a higher limit to avoid regressions elsewhere).

**Comment by alheinecke** [comment]
Would a compile time adjustment be fine (when compiling LIBXSMM for pyfr)?

**Comment by FreddieWitherden** [comment]
Yes, that would be ideal as most of our users compile libxsmm themselves.  Is the code size currently accessible through the makefile?

**Comment by alheinecke** [comment]
Not yet, I was just wondering if this is an acceptable solution.
