### ISSUE TITLE
fsspmdm: double-wide sparse kernel can cause memory corruption

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#504]
Further details are given in issue #501. The double-wide kernel is currently disabled, but enabling it seems to cause memory corruption.

**Comment by FreddieWitherden** [comment]
Do you have a simple reproducer?  I've gone through the code and everything looks to be in order, the only strange bit is:

https://github.com/hfp/libxsmm/blob/master/src/libxsmm_fsspmdm.c#L599

which is the deallocation code for the slower of the kernels.

**Comment by hfp** [comment]
This code is not too strange, it basically avoids a warning with some compilers about casting a function-pointer to a data-pointer. This code is basically to avoid a bulky union-approach, which would also solve the warning.

**Comment by hfp** [comment]
The reproducer for #501 still serves as a reproducer; see [here](https://github.com/hfp/libxsmm/issues/501#issuecomment-896579303). The example always corrupted memory and the code crashed sooner or later for instance in (unrelated) memory deallocation. It's best to run on an AVX-512 capable system (as reported), but I guess it's the same issue anywhere else (if the wider kernel is triggered).
