### ISSUE TITLE
Maximum code size limits sparse kernel performance (fsspmdm) for PyFR

### ISSUE THREAD

**Issue by ChenyuZhang16** [hfp/libxsmm#505]
Hi,
I noticed that LIBXSMM has a maximum kernel size limitation of 128KB, as specified in src/libxsmm_main.c. For some PyFR matrices, e.g. hex 6th order Gauss-Legendre m460, the sparse kernel cannot be generated because the kernel is too large in code size. Therefore, the fallback dense routine is used which is 85% slower than a sparse kernel in this case.

I'm wondering what's the reasoning for setting the maximum kernel size to128 KB. Is it safe if I alter this value manually?

**Comment by alheinecke** [comment]
Please see #502
