### ISSUE TITLE
Build on Apple Silicon (M1, arm64)?

### ISSUE THREAD

**Issue by geoffrey4444** [hfp/libxsmm#508]
I'm one of the developers for a numerical-relativity code called spectre (https://spectre-code.org), and one of its dependencies is libxsmm. Our code supports macOS, but I'm the first to try building on an Apple Silicon (M1, arm64) based Mac.

When I tried compiling libxsmm on my new M1 Mac, I got the "artificial error" that the cpu architecture is unsupported: `error: Intel Architecture or compatible CPU required!`

Is there a way to bypass this error to at least attempt to build libxsmm on arm64? I understand performance will likely not be great, and I understand that this would be unsupported.

**Comment by alheinecke** [comment]
can please post some details of your system and how you attempt to build. The current code should compile on M1 and other arm64&Liunx (we ran on AWS and A64FX) (at least I did it some time back and added fixes for MacOS on M1, but they are only in master, and not part of a release).

**Comment by geoffrey4444** [comment]
Wow, thanks for the supper fast response! I really appreciate it.

I'm running on an M1 iMac (24-inch, M1, 2021) running macOS Big Sur 11.4. I've Xcode and its command-line tools and homebrew. 

I just did `wget https://github.com/hfp/libxsmm/archive/1.16.1.tar.gz -O libxsmm.tar.gz`, unpacked it, cd'd into it, and tried `make CXX=clang++ CC=clang FC=gfortran`. I also tried the "COMPATIBILITY=1" option. Both gave this error:

`include/libxsmm_macros.h:61:5: error: Intel Architecture or compatible CPU required!`

I haven't yet tried building master, since we normally just go with a release, but I'll go ahead and give that a try next! If there's other system information or details of my install attempt that would be helpful for you, please just let me know.

**Comment by geoffrey4444** [comment]
Update: I just cloned and built the master branch, and while I haven't been able to test it with spectre yet (since I'm still working on other dependencies as well), it appeared to build successfully. I'd be happy to close this issue for now but reopen if we have any trouble using the master branch version instead of a released version... thanks again for the quick reply!

**Comment by alheinecke** [comment]
Great! Please let us know how it goes. We have some reports of very rare "Bus errors" on macOS & M1: 1/1000000 JIT fails silently. We are in the process of debugging this, but haven't been lucky so far :-(. On arm64 & Linux these issues don't exist/have not been observed. In general the perf of GEMMs on Neoverse and M1 is as good as on x86 in terms of %peak. 

All element-wise kernels (unary/binary/ternary) have no arm64 support so far. Hence, there is no release :-), but GEMM and batch-reduce GEMM for FP32 and FP64 are fully functional and validated @ highly performance on arm64 (Neoverse, M1, A64FX)
