### ISSUE TITLE
Incorrect results when ldA > K, ldB > N, or ldC > N.  

### ISSUE THREAD

**Issue by jasonsewall** [hfp/libxsmm#51]
As of commit baad5c1, libxsmm_sgemm returns incorrect results when ldA != K, ldB != N, and ldC != N for a row-major configuration. 

Specifically, libsxmm was compiled with

    $ make AVX=2 JIT=1 ROW_MAJOR=1

I've attached a reproducer:
[xmm-bug.zip](https://github.com/hfp/libxsmm/files/61367/xmm-bug.zip)

Edit the makefile to find your local libsxmm, then run

    $ ./xmm-bug 64 240 64 64 240 240 1

You will see that reference C code, MKL, and libxsmm roughly agree on the answers. 

Run 

    $ ./xmm-bug 64 239 64 64 240 240 1

and you will see that MKL and C agree, but libxsmm does not.

**Comment by hfp** [comment]
This is fixed, and a reproducer is available here: https://github.com/hfp/libxsmm/blob/master/tests/rowmajor.c.
