### ISSUE TITLE
Tensor Processing Primitives: A Programming Abstraction for Efficiency and Portability in Deep Learning Workloads

### ISSUE THREAD

**Issue by ProgrammerWLY** [hfp/libxsmm#510]
Hello, can TPP be used as the backend of tensorflow?

**Comment by hfp** [comment]
No, if you refer to an already implemented integration with TensorFlow. Yes, if you want to implement such an integration.

**Comment by hfp** [comment]
Thank you for your participation and asking a question. Feel free to reopen this issue if you have more questions about the paper.
