### ISSUE TITLE
mmfunction dispatch not working

### ISSUE THREAD

**Issue by jasonsewall** [hfp/libxsmm#52]
The libxsmm_mmfunction interface invariably returns 0.

Having built libxsmm like so:

    $ make JIT=1 AVX=2 ROW_MAJOR=1

and the attached code like so:

    $ make -f Makefile.big xmm-dispatch-bug

Run the example:

    $ ./xmm-dispatch-bug 64 240 64 64 240 240 1 

Note the assert that fails. The other call to libxsmm seems to succeed. 

[xmm-dispatch-bug.zip](https://github.com/hfp/libxsmm/files/61464/xmm-dispatch-bug.zip)

**Comment by hfp** [comment]
This is now fixed in the Master branch.
