### ISSUE TITLE
Fails to support MKL as engine 

### ISSUE THREAD

**Issue by gal-star** [hfp/libxsmm#539]
https://github.com/hfp/libxsmm/blob/745e631f66c3b5c0e3cbe94e9d69e04770e25065/samples/deeplearning/gxm/model_zoo/mnist/lenet_train_val.prototxt#L49

Seems like the code is not supporting MKL out-of-the-box. 
The protobuf supports either: LOOP/XSMM enums. So when trying to run:

``
./build/bin/gxm train model_zoo/mnist/lenet_train_val.prototxt model_zoo/mnist/lenet_solver.prototxt 
``

I get the following error:

``
[libprotobuf ERROR google/protobuf/text_format.cc:307] Error parsing text-format gxm.NTGParameter: 50:5: Unknown enumeration value of "MKL" for field "engine".
``
``
Failed to parse ML Parameter file model_zoo/mnist/lenet_train_val.prototxt
``

**Comment by alheinecke** [comment]
GxM is no longer maintained as we are moving to TPPs and pytorch extensions:
https://arxiv.org/abs/2104.05755
We expect that in Q1/21 GxM will be removed from the master source tree.
