### ISSUE TITLE
Update README.md installation requirements for GxM

### ISSUE THREAD

**Issue by gal-star** [hfp/libxsmm#540]
The installation instructions in [GxM](https://github.com/hfp/libxsmm/blob/master/samples/deeplearning/gxm/README.md) documentation should include in addition to the mentioned directories:
1. icpc installed and set on the machine (can be installed from [here](https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit.html#gs.dw8j1h))
2. MKL and OpenMP installed on the machine (as the binary depends on it). 

One can just install [oneAPI package](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html#gs.dw8mqw) on the machine.

**Comment by alheinecke** [comment]
GxM is no longer maintained as we are moving to TPPs and pytorch extensions:
https://arxiv.org/abs/2104.05755
We expect that in Q1/21 GxM will be removed from the master source tree.
