### ISSUE TITLE
Revert of AARCH64 encoding needed

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#548]
@FreddieWitherden : can you please have a look at PR #542 again... I missed something in the review during my vacation and I just realized it when review the SVE stuff.
![image](https://user-images.githubusercontent.com/6407923/140392033-9c6c0035-9a32-48ae-8408-7748c49336af.png)

**Comment by FreddieWitherden** [comment]
The old code should work, as in the old bitwise test will do the job for the two new opcodes as they have the same trailing byte as the existing two opcodes this block is designed to catch (0x83).  So a simple revert will do the job.

**Comment by alheinecke** [comment]
fixed with da01b22
