### ISSUE TITLE
MPSS required, even with MIC=0

### ISSUE THREAD

**Issue by jasonsewall** [hfp/libxsmm#55]
On commit 50ed3d0, my system with ICC 16.0.1 and without MPSS cannot build libxsmm, even with MIC=0:

$ make MIC=0

[jsewall libxsmm (master)]$ make OFFLOAD=0
icc  -Wall -Wno-unused-function -Wno-attributes -fPIC -O2 -ftree-vectorize -ffast-math -funroll-loops   -D__extern_always_inli
ne=inline -DNDEBUG -D__STATIC -D__MKL -Iinclude -Ibuild -I/nfs_home/jsewall/src/libxsmm/src -I/swtools/intel/compilers_and_lib
raries_2016.1.150/linux/mkl/include -mavx2 -c /nfs_home/jsewall/src/libxsmm/src/libxsmm.c -o build/intel64/libxsmm.o
icc: command line warning #10006: ignoring unknown option '-ffast-math'
icc: command line warning #10353: option '-mavx2' ignored, suggest using '-march=core-avx2'
icc: warning #10193: -vec is default; use -x and -ax to configure vectorization
icc: command line warning #10006: ignoring unknown option '-ffast-math'
icc: warning #10362: Environment configuration problem encountered.  Please check for proper MPSS installation and environment
 setup.
icc: warning #10193: -vec is default; use -x and -ax to configure vectorization
In file included from include/libxsmm_frontend.h(35),
                 from include/libxsmm.h(65),
                 from /nfs_home/jsewall/src/libxsmm/src/libxsmm.c(31):
include/libxsmm_macros.h(279): catastrophic error: *MIC* cannot open source file "pthread.h"
  #   include <pthread.h>

I also get warnings about the flag -mavx2, which ICC ignores (-march=core-avx2 is the preferred flag).

**Comment by hfp** [comment]
This is caused by an incomplete installation of Intel Compilers (Makefile.inc: INTEL=0 detected). As you can see, ICC gets GCC-flags instead of our ICC-specific flag set (which would include -no-offload. This is caused by having not installed IFORT.

**Comment by hfp** [comment]
Hi Jason,

if the above is not true, can you have a look at the mechanism in Makefile.inc (look for the "INTEL" variable).

Btw, thanks for your nicely focused bug reports!
Hans
