### ISSUE TITLE
BF16t o FP32 Kernels break for certain matrix dimensions

### ISSUE THREAD

**Issue by UIsken** [hfp/libxsmm#561]
On Ubuntu 20.04 and rhl fedora 8 the matrix kernels in BF16 to FP32 precision breaks for certain matrix sizes. This regards all functions for bfloat16 to fp32 precision, namely libxsmm_bsmmdispatch(), libxsmm_xmmdispatch(), and libxsmm_bsmmfunction().

When the matrix size of "K" is bigger then 17 then matrix kernel breaks. I tried this with both SDE64 emulation (cooperlake) on an i5 and on an actual Cooperlake and both didn't work. It looks like the matrix kernel is computing wrong numbers for smaller sizes when "M" or "N" are bigger then 17 and "K" stays small, but it doesn't crash. 

For reproduction: I used  samples/xgemm from this repository with following setup:
```
~$ ./kernel 16 16 17 16 17 16 1 1 0 0 0 0 nopf BF16F32 nobr 0 0 1
------------------------------------------------
RUNNING (16x17) X (17x16) = (16x16), BF16F32, BR=1
------------------------------------------------
JIT failed, please run with LIBXSMM_VERBOSE=-1 and/or with debug mode LIBXSMM library!
```
```
~$ LIBXSMM_VERBOSE=-1 ./kernel 16 16 17 16 17 16 1 1 0 0 0 0 nopf BF16F32 nobr 0 0 1
------------------------------------------------
RUNNING (16x17) X (17x16) = (16x16), BF16F32, BR=1
------------------------------------------------
LIBXSMM: prepared to pin threads.
LIBXSMM ERROR (libxsmm_generator_gemm_kernel): unknown architecture or unsupported precision (error #90004)!
JIT failed, please run with LIBXSMM_VERBOSE=-1 and/or with debug mode LIBXSMM library!

LIBXSMM_VERSION: idc_transpose-1.16.1-1008 (25183216)
CPX/SP      TRY    JIT    STA    COL
   0..13      0      0      0      0 
  14..23      1      0      0      0 
  24..64      0      0      0      0 
Registry and code: 14 MB
Uptime: 0.001711 s
```

**For reference:**

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              448
On-line CPU(s) list: 0-447
Thread(s) per core:  2
Core(s) per socket:  28
Socket(s):           8
NUMA node(s):        8
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8376H CPU @ 2.60GHz
Stepping:            11
CPU MHz:             3347.393
CPU max MHz:         4300.0000
CPU min MHz:         1000.0000
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0-27,224-251
NUMA node1 CPU(s):   28-55,252-279
NUMA node2 CPU(s):   56-83,280-307
NUMA node3 CPU(s):   84-111,308-335
NUMA node4 CPU(s):   112-139,336-363
NUMA node5 CPU(s):   140-167,364-391
NUMA node6 CPU(s):   168-195,392-419
NUMA node7 CPU(s):   196-223,420-447
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

**Emulated machine:**

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Stepping:                        10
CPU MHz:                         1800.000
CPU max MHz:                     3400,0000
CPU min MHz:                     400,0000
BogoMIPS:                        3600.00
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB fil
                                 ling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi 
                                 mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon
                                  pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monit
                                 or ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcn
                                 t tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb 
                                 invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgs
                                 base tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt 
                                 xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_
                                 epp md_clear flush_l1d

**Comment by alheinecke** [comment]
This is expected: BF16 needs K%2 == 0 as this is the instruction in hardware.

**Comment by UIsken** [comment]
This answers my question what to do when using the vnni format for uneven "K", but which is optional right? 
Does this rule apply for all sizes of "K", or just for big one? - Since my small homebrew kernels worked all perfectly.

Thanks for the fast answer,
Regards

**Comment by alheinecke** [comment]
No you will get JIT-fails for every uneven K.... or you run BF16_FLAT (which is running at FP32 speed). You need to prepare A in VNNI format, which needs K%2==0, otherwise VNNI instructions don't work, simply as they do 32bit accesses (in hardware).

**Comment by UIsken** [comment]
Thank you for your fast reply, you helped me a lot!
