### ISSUE TITLE
libxsmm-1.16.1 error when building CP2K v8.2

### ISSUE THREAD

**Issue by tanoury1** [hfp/libxsmm#562]
Hi,
I have build several versions of CP2K, but for v 8.2 I have run into a libxsmm error.  I built libxsmm  using Intel 2021.3 compilers and MKL on a RHEL v7.2 system running GCC 10.3.0. The error output from the CP2K compile is attached.

[LIBXSMM_ERROR.txt](https://github.com/hfp/libxsmm/files/7598790/LIBXSMM_ERROR.txt)

Thank you so much for your help,
Jerry

**Comment by hfp** [comment]
The problem stems from v1.16.x not being validated against GCC 10.x (or GCC 10.x introduced later than any v1.16.x release). Though, GCC 10.x implied some reasonable changes or departure from previous default behavior like `-fcommon` and `-fno-common`. The most clean solution is back-porting master/main's build system to v1.16.x, i.e., a new release like v1.16.4.

**Comment by hfp** [comment]
[LIBXSMM 1.17](https://github.com/hfp/libxsmm/releases/tag/1.17) fixes this issue. I will hence close this issue as resolved. Thank you for your contribution and report!
