### ISSUE TITLE
Error while running DL samples of tpp on Mac(M1)

### ISSUE THREAD

**Issue by IsolatedMy** [hfp/libxsmm#566]
I wanna execute DL samples of TPP in folder [fullyconnected_tpp](https://github.com/hfp/libxsmm/tree/master/samples/deeplearning/fullyconnected_tpp). After I did `make` in the project folder, I ran `make` in the folder [fullyconnected_tpp](https://github.com/hfp/libxsmm/tree/master/samples/deeplearning/fullyconnected_tpp) as follows:
```shell
$ fullyconnected_tpp ls                                
Makefile                 layer_example_bf16_amx.c run_fc_layers.sh
layer_example_bf16.c     layer_example_f32.c      run_fullyconnected.sh
$ fullyconnected_tpp make
cc -DNDEBUG -DLIBXSMM_NOFORTRAN  -I. -I../../../include -fPIC -g -Wno-pass-failed -Wall -O2 -pthread  -c layer_example_f32.c -o obj/layer_example_f32-c.o
cc -o layer_example_f32 obj/layer_example_f32-c.o -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmmext.a -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmm.a -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmmnoblas.a -lm -ldl -lstdc++
cc -DNDEBUG -DLIBXSMM_NOFORTRAN  -I. -I../../../include -fPIC -g -Wno-pass-failed -Wall -O2 -pthread  -c layer_example_bf16_amx.c -o obj/layer_example_bf16_amx-c.o
layer_example_bf16_amx.c:723:23: error: implicit declaration of function '__mmask32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  LIBXSMM_VLA_DECL(4, __mmask32,  relubitmask, ((cfg.fuse_type & MY_ELTWISE_FUSE_RELU) == MY_ELTWISE_FUSE_RELU) ? (__mmask32*)relu_ptr : NULL, nBlocksOFm, cfg.bn, cfg.bk/32);
# the complete error log is attached 
17 errors generated.
$ fullyconnected_tpp ls                                
Makefile                 layer_example_f32        run_fc_layers.sh
layer_example_bf16.c     layer_example_f32.c      run_fullyconnected.sh
layer_example_bf16_amx.c obj
```
The complete error log is attached in [issue.md](https://github.com/hfp/libxsmm/files/7692890/issue.md). The excutable file `layer_example_f32` can be generated successfully, while there is errors generating `layer_example_bf16`. I tried to execute `layer_example_f32`, but it failed like this:

```shell
$ ./layer_example_f32              
##########################################
#          Setting Up (Common)           #
##########################################
PARAMS: N:256  C:1024  K:1024
PARAMS: ITERS:10
SIZE Input  (MB):       1.00 MiB
SIZE Output (MB):       1.00 MiB
SIZE Input   (1):       0.00 MiB
SIZE Output  (1):       0.00 MiB
SIZE Filter     :       4.00 MiB
##########################################
#         Computing Reference ...        #
##########################################
##########################################
#      Computing Reference ... done      #
##########################################

##########################################
#      Setting Up  (custom-Storage)      #
##########################################
JIT for TPP fwd_zero_kernel failed. Bailing...!
```

It seems problem occured when running to the [layer_example_f32.c:326](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_f32.c#L326), but I have no idea what happened. In a word, I want to know whether there is a tutorial for me to run the samples in folder [fullyconnected_tpp](https://github.com/hfp/libxsmm/tree/master/samples/deeplearning/fullyconnected_tpp). If possible, I hope 
you could help me solve the current problems. My enviroment is as follows:

```
Operating system: macOS Big Sur 11.6
CPU: Apple M1
```

**Comment by hfp** [comment]
First look tells the sample code is not ported like contains x86 specific code. We should make compilation conditional such that this specific sample (layer_example_bf16_amx.c) compiles and only prints a message like not supported on this architecture.

**Comment by hfp** [comment]
As a workaround you can try invoking some specific Make targets (other than `layer_example_bf16_amx` included in default/all target):

```bash
make layer_example_f32
make layer_example_bf16
```

**Comment by IsolatedMy** [comment]
Following your advice, I try to just invoke target `layer_example_f32`. The problem still exists:

```shell
sh-3.2$ make layer_example_f32
cc -DNDEBUG -DLIBXSMM_NOFORTRAN  -I. -I../../../include -fPIC -g -Wno-pass-failed -Wall -O2 -pthread  -c layer_example_f32.c -o obj/layer_example_f32-c.o
cc -o layer_example_f32 obj/layer_example_f32-c.o -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmmext.a -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmm.a -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmmnoblas.a -lm -ldl -lstdc++
sh-3.2$ file layer_example_f32
layer_example_f32: Mach-O 64-bit executable arm64
sh-3.2$ ./layer_example_f32 
##########################################
#          Setting Up (Common)           #
##########################################
PARAMS: N:256  C:1024  K:1024
PARAMS: ITERS:10
SIZE Input  (MB):       1.00 MiB
SIZE Output (MB):       1.00 MiB
SIZE Input   (1):       0.00 MiB
SIZE Output  (1):       0.00 MiB
SIZE Filter     :       4.00 MiB
##########################################
#         Computing Reference ...        #
##########################################
##########################################
#      Computing Reference ... done      #
##########################################

##########################################
#      Setting Up  (custom-Storage)      #
##########################################
JIT for TPP fwd_zero_kernel failed. Bailing...!
```

And I find the errors( in the  [issue.md](https://github.com/hfp/libxsmm/files/7692890/issue.md) ) during the compilation of target `layer_example_bf16` mostly point to "use of undeclared identifier 'relubitmask_'", so I comment these lines(layer_example_bf16.c:[886](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_bf16.c#L886), [950](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_bf16.c#L950), [978](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_bf16.c#L978), [1010](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_bf16.c#L1010), [1086](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_bf16.c#L1086), [1118](https://github.com/hfp/libxsmm/blob/cecc416b8ee68a332e089220215b3a18e46d5e38/samples/deeplearning/fullyconnected_tpp/layer_example_bf16.c#L1118)). Now I can make the target `layer_example_bf16`, although the executable file output errors too.

```shell
sh-3.2$ make -B layer_example_bf16
cc -DNDEBUG -DLIBXSMM_NOFORTRAN  -I. -I../../../include -fPIC -g -Wno-pass-failed -Wall -O2 -pthread  -c layer_example_bf16.c -o obj/layer_example_bf16-c.o
cc -o layer_example_bf16 obj/layer_example_bf16-c.o -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmmext.a -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmm.a -L/Users/chenmingyu/workspace/github/libxsmm/lib/ ../../../lib/libxsmmnoblas.a -lm -ldl -lstdc++
sh-3.2$ ls
Makefile			layer_example_f32.c
layer_example_bf16		obj
layer_example_bf16.c		run_fc_layers.sh
layer_example_bf16_amx.c	run_fullyconnected.sh
layer_example_f32
sh-3.2$ ./layer_example_bf16 
##########################################
#          Setting Up (Common)           #
##########################################
PARAMS: N:256  C:1024  K:1024
PARAMS: ITERS:10
SIZE Input  (MB):       0.50 MiB
SIZE Output (MB):       0.50 MiB
SIZE Input   (1):       0.00 MiB
SIZE Output  (1):       0.00 MiB
SIZE Filter     :       2.00 MiB
##########################################
#         Computing Reference ...        #
##########################################
##########################################
#      Computing Reference ... done      #
##########################################

##########################################
#      Setting Up  (custom-Storage)      #
##########################################
JIT for BRGEMM TPP gemm_fwd failed. Bailing...!
```

**Comment by alheinecke** [comment]
aarch64 support is experimental, M1 support is highly experimental. For aarch64 there is only FP32.

 LIBXSMM_TARGET=aarch64 ./layer_example_f32  works on M1... but OpenMP needs to be installed from homebrew etc. on macos

**Comment by IsolatedMy** [comment]
Now it works. Thanks.
