### ISSUE TITLE
Intel AMX BF16 Convolution Support

### ISSUE THREAD

**Issue by parvizmp** [hfp/libxsmm#572]
Is there any guidance for running ResNet50 convolutions on AMX via SDE?
Are there any particular limitations in the latest release with respect to AMX for BF16 or INT8?
For instance using libxsmm `1.17` and SDE `9.0` I'm getting:
```
$ sde -spr -- ./layer_example_bf16 1  224 224 1  3 64 7 7 3 3 2 F L 0
LIBXSMM: prepared to pin threads.
LIBXSMM WARNING: library is optimized without -DNDEBUG and contains debug code!
LIBXSMM WARNING: timer is maybe not cycle-accurate!
##########################################
#    Setting Up Common    #
##########################################
PARAMS: W:224  H:224  N:1  C:3  K:64  R:7  S:7  P:112  Q:112  STRIDE:2
PARAMS: ITERS:1
InImg 224x224 Padded (224x224)
OutImg 112x112 Padded (112x112)
SIZE Input  (MB):       0.29 MiB
SIZE Output (MB):       1.53 MiB
SIZE Input   (1):       0.29 MiB
SIZE Output  (1):       1.53 MiB
SIZE Weight     :       0.02 MiB
LIBXSMM WARNING: locked-page watermark reached at 64 MB!
##########################################
#         Computing Reference ...        #
##########################################
##########################################
#      Computing Reference ... done      #
##########################################
 
##########################################
#     Setting Up    (custom-Storage)     #
##########################################
LIBXSMM DNN Error: Invalid padding was specified!
LIBXSMM DNN Error: An invalid handle was provided!
LIBXSMM DNN Error: Tensor creation failed!
Segmentation fault (core dumped)
```
Thanks!

**Comment by alheinecke** [comment]
please use master and as the error message says invalid padding as logical padding is not supported for BF16, also inner product dimension cannot be 3 given the BF16 datatype and VNNI layouts.

**Comment by parvizmp** [comment]
Thanks I'll use `master`. I noticed in the code logical padding isn't yet supported but was confused by the error since I thought padding was disabled via the last argument.

I can explicitly pad the C dimension per the VNNI factor - is this something that will be done automatically by libxsmm in the future?

**Comment by alheinecke** [comment]
We are right now retiring all these convolutions and we are merging to clean & lean TPP-based implementation, https://arxiv.org/abs/2104.05755 . A sneak peak preview can be found here: https://github.com/hfp/libxsmm/tree/enable_gemm_in_eqs/samples/deeplearning/cnn_tpp .

So we are moving away for pre-packaged library to very crisp and easily tunable code due to the use of the TPP virtual tensor ISA. Here one can easily add these paddings etc.
