### ISSUE TITLE
routines in libxsmm don't obey BETA=0

### ISSUE THREAD

**Issue by maxhutch** [hfp/libxsmm#6]
The inlined routines `libxsmm_{s,d}imm` and `libxsmm_{s,d}blasmm` generated in libxsmm.f90 hardcode `beta = 1` even when built with `BETA=0`.

**Comment by alheinecke** [comment]
That's correct:-) That's why BETA=0 is not documented. BETA=0 currently applies to the ASM backend only.

**Comment by maxhutch** [comment]
I didn't it manually without any trouble.  If I can figure out how `libxsmm_interface.py` get's BETA, I'll just put it in the template.

**Comment by maxhutch** [comment]
I think I got it.  Might I suggest migrating some of this command line args to json files?

**Comment by alheinecke** [comment]
Sure! That would be great! I'll will push some changes soon which store the offload settings.

**Comment by alheinecke** [comment]
hehe not the json, changing the py scritps. Json, I haven't though about.

**Comment by maxhutch** [comment]
#7 handled the fortran case.  The C case may not be fixed.

**Comment by alheinecke** [comment]
Thanks for the fix. Please note, we’re experiencing performance problems with the f90 interface (2X!!) which we haven’t root caused so far.

Alex

**Comment by alheinecke** [comment]
the latest commit (https://github.com/hfp/libxsmm/commit/e37c9dc8176b4042efb005d5b2d30b4b912f7266) should fix this for C/C++ as well.
