### ISSUE TITLE
Make LIBXSMM available for Microsoft Windows OS

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#71]
The following work needs to be completed as part if this issue:
- JIT code generation for non-PREFETCH kernels (executable buffer, etc.)
- Build system (Makefile based plus Cygwin/MinGW GNU Make, ICC/VCC, etc.)
- Continuous Integration coverage

Please note that building with PREFETCH and using it (user code) will work, however adjusting the calling convention to cover up the required number of arguments is not part of this issue (PREFETCH becomes essentially a no-op until the code is reworked for a scheme portable across calling conventions).

Please also note that the current version (and any previous version of LIBXSMM) had/has some limited functionality under Windows already (see [ide](https://github.com/hfp/libxsmm/tree/master/ide) folder).

**Comment by hfp** [comment]
Current status: the JIT-generated code needs to be adapted for the calling convention under Windows. To keep the changes in bounds, the prolog/epilog will be adapted to provide the arguments according to the Linux calling convention. In general, the Windows calling convention negatively impacts the performance of small kernels under Windows.

**Comment by hfp** [comment]
Moved this issue to https://github.com/hfp/libxsmm/wiki/Development#longer-term-issues.

**Comment by RoyiAvital** [comment]
What's the current status on Windows?

**Comment by alheinecke** [comment]
I have it working a private branch for GEMM only for AVX2. Still need to verify for AVX512. Then we will make available in master. I would guess ~2weeks.
