### ISSUE TITLE
about ROW_MAJOR

### ISSUE THREAD

**Issue by hqzhou** [hfp/libxsmm#80]
dear developers,

I just want to know when we need to use column major or row major? Is it related to
whether the program is written in C/C++ or in FORTRAN?

Thanks!

-- Huiqun Zhou

**Comment by hqzhou** [comment]
Hans,

Thank you very much!

FORTRAN keeps array in column major mode in memory while C/C++ in row major. As BLAS, LAPACK
were implemented in FORTRAN, libxsmm, when interfaces with BLAS, needs to be column major, too. 
So, in fact, which major should be used still depends on which programming language is in use. For 
example, if one wants to modify libxsmm to interface with CUBLAS, one must compile libxsmm in row 
major, I think. 
 
Thanks again.

Huiqun Zhou
 

------------------ Original ------------------

**Comment by hfp** [comment]
Let me put it this way: if your matrices are stored in row-major order, you can still call BLAS by either transposing the matrices, or by twiddling the arguments. In LIBXSMM, transposes are currently falling back to BLAS i.e., one better twiddles the arguments. Please note that twiddling the arguments not only sticks to BLAS (no need for the CBLAS interface), but is rather simple given that we are not talking about complex number matrices.

Here is an example in C which assumes that the matrices are initialized in a C-natural i.e., row-major order (not pre-transposed during initialization):

```C
const char notrans = 'N', trans = 'T';
libxsmm_dgemm(&notrans, &notrans, &n, &m, &k, &alpha, b, &ldb, a, &lda, &beta, c, &ldc);
libxsmm_dgemm(&trans, &trans, &m, &n, &k, &alpha, a, &lda, b, &ldb, &beta, c, &ldc);
```

Both of the above calls are equivalent, and handle the operands correctly while producing the correct result (in row-major order). However, when you configure LIBXSMM with ROW_MAJOR=1, you could write:

```C
libxsmm_dgemm(&notrans, &notrans, &m, &n, &k, &alpha, a, &lda, b, &ldb, &beta, c, &ldc);
```

The latter somewhat turns LIBXSMM's BLAS interface into a CBLAS interface.

**Comment by alheinecke** [comment]
I believe the example above is not correct. BLAS specifies that all three matrices are column major. If you use column major layout, you cannot use (CU)BLAS right away.

If you want to use BLAS with row-major you simply exchange A and B and provide a row-major C matrix

When using transA=transB='T' C is still in column major, so will lead to problems in applications which assume that C is row-major.

So 
const char notrans = 'N', trans = 'T';
libxsmm_dgemm(&notrans, &notrans, &n, &m, &k, &alpha, b, &ldb, a, &lda, &beta, c, &ldc);
libxsmm_dgemm(&trans, &trans, &m, &n, &k, &alpha, a, &lda, b, &ldb, &beta, c, &ldc);
are not equivalent, I guess:

First one:

       _____
       _____
       _____
       _____
___                   _____
___                   _____
___               =  _____
___                   _____

Second on:

       _____
       _____
       _____
       _____
___                   |   |   |   |
___                   |   |   |   |
___               =  |   |   |   |
___                   |   |   |   |

**Comment by alheinecke** [comment]
sorry github is reformatting...

**Comment by hfp** [comment]
You're right, and I've updated my comment (and removed the cluttered ASCII art). So:

> (1) Gives C^T, interpreting in RM storage gives C.
> (2) Gives C, interpreting in RM storage gives C^T.
> (3) Gives C^T, interpreting in RM storage gives C.

So (1) and (2) are suitable for programs working with row-major storage, whereas (2) allows e.g., to pass the result into code which assumes column-major storage. As pointed out already, (2) is not supported by LIBXSMM right now due to transpose being not supported.

To go back to the original question about ROW_MAJOR configuration, all I wanted to say is: do it like (1) in order to stay in BLAS-style rather than re-configuring LIBXSMM (unless one really wants CBLAS). So given that (CU)BLAS is also BLAS-style, one can replace those calls in a "1:1 fashion" using LIBXSMM and there is no need to touch ROW_MAJOR.
