### ISSUE TITLE
LIBXSMM cannot be executed within valgrind

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#81]
As LIBXSMM uses MMAP when creating the executable code buffers, valgrind crashes with seg.faults, c.f. http://stackoverflow.com/questions/27382653/mmap-return-einval-when-run-with-valgrind 
Not sure how we can handle this in LIBXSMM!

How to reproduce the behavior:
make realclean
make DBG=2
cd samples/jit_generator
./test_xGEMM.sh
valgrind --smc-check=all ./xgemm_icc 32 32 32 32 32 32 1 1 1 1 snb nopf SP 10

Intel SDE is fine:
sde64 -snb -ptr_check 1 -smc 2  -- ./xgemm_icc 32 32 32 32 32 32 1 1 1 1 snb nopf SP 10

**Comment by hfp** [comment]
Fixed in fb6279b.
