### ISSUE TITLE
Remove BLAS library dependency

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#82]
A feature should be added to allow linking LIBXSMM without specifying a BLAS library into an application/library. In fact, LIBXSMM should either provide its own simple implementation (for correctness) or error out. 

Background: if LIBXSMM is used to implement BLAS functionality as a building block one cannot link to the library which is currently being built. In this case the fall back is not need as it is for some other usages scenarios of LIBXSMM. So what about FALLBACK=0? I tried already building with BLAS=0, but it still requires sgemm and degemm:
 ./../../lib/libxsmm.a(libxsmm.o): In function `__real_sgemm_':
libxsmm.c:(.text+0x2d61): undefined reference to `sgemm_'
./../../lib/libxsmm.a(libxsmm.o): In function `__real_dgemm_':
libxsmm.c:(.text+0x2d71): undefined reference to `dgemm_'

**Comment by alheinecke** [comment]
I think a simple 6 nested loops implementation would do the trick which defines sgemm_ and dgemm_. Will provide. Then we compile this into libxsmmblasstub.a/so and one can link with -lxsmm -lxsmmblasstub .

**Comment by hfp** [comment]
I think no such work is needed. We already have all ingredients in particular the "omp" implementation can already be turned into a "big gemm" using an environment variable. Right now, this can fail if JIT fails for whatever reason. Those reasons include unsupported kernels (with transpose). An general implementation with arbitrary Alpha and Beta is also somewhat available via the frontend (former "inline" implementation, which is kept around but does not support arbitrary GEMM either). On the other hand, transposes are on their way. I think the next step towards such an implementation without the need for fallback-BLAS is to complete the stand-alone transposes (in-place transpose is missing). Perhaps the JIT-based transpose kernels will arrive in the meanwhile, and everything can be put together this year.

**Comment by alheinecke** [comment]
Then also the threshold needs to disappear. This is for codes which just have small GEMMs and now need to build OpenBLAS or link against BLAS library which is never called. It's not about the functionality, but the linkage of the application. Can we disable the BLAS dependency for now using a build option (and yes, it can break if people using this incorrectly,

**Comment by hfp** [comment]
Ok, this relaxes the requirements. I am about to release 1.4.4 and this relaxation might be enough to include this request into this release. I will look into it.

**Comment by alheinecke** [comment]
Unfortunately, I'm still seeing during linkage:
build/submodules/libxsmm/lib/libxsmm.a(libxsmm.o): In function `__real_sgemm_':
libxsmm.c:(.text+0x31a1): undefined reference to `sgemm_'
build/submodules/libxsmm/lib/libxsmm.a(libxsmm.o): In function `__real_dgemm_':
libxsmm.c:(.text+0x31b1): undefined reference to `dgemm_'
scons: *** [build/edge] Error 1

**Comment by hfp** [comment]
The first commit for this issue is by no means the last one (I would mark the issue as resolved if it is ready). Are you seeing the linker errors during regular use, or did you already apply BLAS=0? The latter is not ready, and an linker error is expected.

**Comment by alheinecke** [comment]
both, with and without BLAS=0

**Comment by hfp** [comment]
I will look into it. The issue is also that it's not caught by or CI. Anyhow, I may release version 1.4.4 without this feature to lower risk for more issues.

**Comment by hfp** [comment]
Can you show the exact make command? I cannot reproduce the problem.

**Comment by alheinecke** [comment]
make realclean && make
and then linking the application which uses LIBXSMM with:
icpc -o build/foo -Lsubmodules/libxsmm/lib -lxsmm
build/submodules/libxsmm/lib/libxsmm.a(libxsmm.o): In function `__real_sgemm_':
libxsmm.c:(.text+0x31a1): undefined reference to `sgemm_'
build/submodules/libxsmm/lib/libxsmm.a(libxsmm.o): In function `__real_dgemm_':
libxsmm.c:(.text+0x31b1): undefined reference to `dgemm_'

**Comment by hfp** [comment]
Ok, that's expected and not related to the recent change. The reason is the static linker-wrapper, which is requiring ?gemm routines. Since BLAS is not a hard dependency, the actual application is *always* asked to link against BLAS. Removing this requirement is a different but very related to this issue. I will check if I can do something with weak symbols.

**Comment by alheinecke** [comment]
the current workaround is kind of weird:
1. adding an additional submodule to the project: OpenBLAS
2. compiling this submodule
3. linking with: icpc/g++ -o build/foo -Lsubmodules/libxsmm/lib -lxsmm -Lsubmodules/OpenBLAS -lopenblas

**Comment by alheinecke** [comment]
yes but BLAS is never called in these applications and it creates an additional burden, the issues shows especially up on Cray systems with static linkage being default/the must.

**Comment by alheinecke** [comment]
Quick update I tried this and the linking goes well, however libxsmm_xmmdispatch seems to return NULL now.

**Comment by hfp** [comment]
There is nothing to try yet as the whole CI is broken. I will report back once finished.

**Comment by hfp** [comment]
The build now passes again after revamping the static/dynamic call interception. As discovered in the above discussion, this issue is more about to get rid of an actual BLAS dependency when not calling any BLAS-related function in LIBXSMM rather than being able to get rid of the BLAS-fallback in general. The latter has far more prerequisites e.g., transposes.

**Comment by hfp** [comment]
To get rid of the BLAS dependency, one need to link against libxsmm and libxsmmext in this order. An additional option is still being investigated (building LIBXSMM with BLAS=0).

**Comment by hfp** [comment]
Introduced an additional option to remove BLAS library dependency. When building LIBXSMMM with BLAS=0, a user permits that BLAS is never called (also not via fall-back code path e.g., if JIT fails or if the kernels is out of range or otherwise unsupported), otherwise the library call may die ungracefully. Another option is to simply link libxsmmext after linking libxsmm (link order matters). The latter enables this feature in a more selective fashion, and without the need for a special build of LIBXSMM.

**Comment by hfp** [comment]
Finally fixed and documented.
