### ISSUE TITLE
NNpack

### ISSUE THREAD

**Issue by bhack** [hfp/libxsmm#87]
Do you see any partial overlap with https://github.com/Maratyszcza/NNPACK?

**Comment by hfp** [comment]
It looks like there is some overlap, thanks or sharing!

We see LIBXSMM as a library to provide primitives which are neutral wrt an actual application, however development is driven by and optimized for actual applications including ML.

**Comment by bhack** [comment]
Intel is also contributing to this special kernels https://github.com/google/gemmlowp

**Comment by jeffhammond** [comment]
@Maratyszcza may be interested in discussing this topic 😄

**Comment by hfp** [comment]
Regarding "neutral wrt an actual application" -- I believe LIBXSMM is not an application-specific library. However, we use actual applications to drive our development. If you look at the master revision you will find support for small convolutions, which was not there at the time where this discussion started. Regarding low precision *GEMM*, we have not immediate plans to cover lower precision types.

**Comment by hfp** [comment]
Our DNN API will be released soon for the first time (it has been available with LIBXSMM/master since more than a month [Intel Developer Forum IDF'16]). With respect to lower precision, this API supports lower precision and will further build up the related functionality.

**Comment by bhack** [comment]
Do you have any link to presentation slides?

**Comment by hfp** [comment]
We maintain a presentation for our event coverage, but do not share it outside of an event or via general download. I will send you (privately) what I have incl. the CHANGELOG of the upcoming release. However, at this point the DNN API is not covered in our presentation slides (other than by a single overview slide).

**The best source of information is our reference documentation:**
https://github.com/hfp/libxsmm/#interface-for-convolutions (also as [PDF](https://github.com/hfp/libxsmm/raw/master/documentation/libxsmm.pdf))

We also have an artificial question (and answer) in our intro of the reference documentation, which goes as follows:
> **What is a small convolution?** In the last years, new workloads such as deep learning and more specifically convolutional neural networks (CNN) emerged, and are pushing the limits of today's hardware. One of the expensive kernels is a small convolution with certain kernel sizes (3, 5, or 7) such that calculations in the frequency space are not the most efficient method when compared with direct convolutions. LIBXSMM's current support for convolutions aims for an easy to use invocation of small (direct) convolutions, which are intended for CNN training and classification. The Interface is currently ramping up, and the functionality increases quickly towards a more general use.

**Comment by hfp** [comment]
@bhack I don't have your email address -- can you drop me a quick mail?
My address follows the forename.name @ intel.com scheme (see https://github.com/hfp for the name).
