### ISSUE TITLE
inernal_transpose_oop

### ISSUE THREAD

**Issue by jeffhammond** [hfp/libxsmm#89]
inernal_transpose_oop in https://github.com/hfp/libxsmm/blob/master/src/libxsmm_transpose.c either points to something that hasn't been implemented yet or won't point to the right symbol, which I assume will be named internal_transpose_oop.

**Comment by alheinecke** [comment]
I can build the transpose example without any problems. https://github.com/hfp/libxsmm/tree/master/samples/transpose
make realclean && make
cd samples/transpose
make

**Comment by jeffhammond** [comment]
Presumably because inernal_transpose_oop is dead code.

I am really just pointing out the spelling error because I'm OCD...

**Comment by alheinecke** [comment]
the spelling error goes through the entire file, so this is "fine". However, for size the code seems to be slow, mainly due to NTS I guess.

**Comment by hfp** [comment]
Jeff, thanks for reporting! I've fixed the spelling issue. The internal_transpose_oop function is an auxiliary function which builds the cache-oblivious call tree for a block-wise out-of-place transpose. It's not dead code but serves the implementation of `libxsmm_transpose_oop` (it's called here: https://github.com/hfp/libxsmm/blob/master/src/libxsmm_transpose.c#L131).

Regarding slowness, I believe it's not too bad and the sample code compares performance (which looks competitive to me). However, right now the transpose is not parallelized (a parallelized implementation would be provided by libxsmmext).

In fact the transpose code is a new feature which just builds up, and it is not even documented (yet). Next step would be a high-performing in-place transpose followed by parallelizing all transposes. Jeff, do you have a use case for stand-alone in-place or out-of-place transposes?

**Comment by alheinecke** [comment]
I think before having an in-place transpose we need fast small transposes oop. I don't see how parallelization would help here, e.g when transposing a 13x13 matrix. They are particular important for small GEMMs. For big gemms no transpose feature is needed as this would happen when copying into blocks.

**Comment by jeffhammond** [comment]
Fast OOP transpose is incredibly useful for tensor computations.  NWChem spends quite a bit of time in these operations.

A long time ago, I devoted a lot of effort to implementing OOP tensor transpose kernels for NWChem.  https://github.com/jeffhammond/spaghetty/ has details, although it is a bit embarrassing how simple-minded I was in hindsight (the work was done when I was a chemistry graduate student - please don't judge me).

https://github.com/HPAC/TTC is a more recent effort that I consider much better.

I do not have any use for IP transpose, but https://github.com/bryancatanzaro/inplace and the associated paper demonstrate they have value to some.

If I was interested in IP transpose, it would be because of reducing the memory footprint relative to OOP, but I can achieve that with a blocked transpose that uses OOP on blocks but is IP otherwise, since this adds a constant memory overhead of twice the bytes required for a block.

One cannot, in general, do tensor transposes IP because computing the cycles required can be more expensive than the transpose itself.  I can't remember the details, but one of my students at Argonne spent a lot of time on this and I'm confident that his conclusion was correct.

**Comment by alheinecke** [comment]
Please specify the sizes the transpose and if they and following GEMM should run multi or single threaded
