### ISSUE TITLE
complex and mixed types

### ISSUE THREAD

**Issue by jeffhammond** [hfp/libxsmm#97]
This has been discussed offline, but I am creating an issue for it so that (1) people know that it has been requested before, (2) people can vote on the issue if they want this feature, and (3) the developers can comment on the merits of these requests.

complex = complex single, complex double
mixed = e.g. real double + complex double

**Comment by hfp** [comment]
There are no (immediate) plans to support more types in LIBXSMM/GEMM.

**Comment by hfp** [comment]
I have covered this in our [Q&A section of the Wiki](https://github.com/hfp/libxsmm/wiki/Q&A) with two artificial questions: (1) [What about complex and mixed types](https://github.com/hfp/libxsmm/wiki/Q&A#what-about-complex-and-mixed-types), and (2) [What about voting for features?](https://github.com/hfp/libxsmm/wiki/Q&A#what-about-voting-for-features)

**Comment by hfp** [comment]
Update: https://github.com/hfp/libxsmm/issues/227#issuecomment-401273729
